CLASS zcl_generate_country DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
          INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_GENERATE_COUNTRY IMPLEMENTATION.


 METHOD if_oo_adt_classrun~main.

    DATA itab TYPE TABLE OF ztab_country.


* fill internal travel table (itab)
itab = VALUE #(

 ( country = 'Kosovo'         rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Virgin Islands, British'        rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Sint Maarten (Dutch part)'          rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Obsolete see NL territory'          rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Trinidad and Tobago'        rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Guinea'     code = 'Guinea'     rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Congo'      code = 'Congo'      rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Cote d Ivoire'      code = 'CI'     rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Brunei Darussalam'      code = 'BN'     rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'PALESTINE'          rating = 'D-High Risk'     isactive = 'Yes' )
 ( country = 'Zimbabwe'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Zambia'     code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Yemen'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Wallis & Futuna'    code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Viet Nam'       rating = 'Mid Term-C Short Term-Sensitive'     isactive = 'Yes' )
 ( country = 'Venezuela'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Vatican City'   code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Vanuatu'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Uzbekistan'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'US Virgin Islands'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'US Minor Outlying Islands'      code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Uruguay'    code = ''   rating = 'Mid Term-BB ; Short Term-Medium'     isactive = 'Yes' )
 ( country = 'United States'      code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'United Kingdom'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'United Arab Emirates'       rating = 'Mid Term-BB , Short Term-Low'    isactive = 'Yes' )
 ( country = 'Ukraine'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Uganda'     code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Tuvalu'     code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Turks & Caicos'     code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Turkmenistan'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Turkey'     code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Tunisia'    code = ''   rating = 'Mid Term-C ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Trinidad & Tobago'      code = ''   rating = 'Mid Term-B ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Tonga'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Tokelau'    code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Togo'   code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Timor Leste'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Thailand'   code = ''   rating = 'Mid Term-B ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Tanzania, United Republic of'       rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Tajikistan'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Taiwan'     code = ''   rating = 'Mid Term-A ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Syria'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Switzerland'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Sweden'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Swaziland'      code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Svalbard & Jan Mayen'   code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Suriname'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Sudan'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'St. Vincent & The Grenadines'   code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'St. Pierre Et Miquelon'     code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'St. Maarten'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'St. Lucia'      code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'St. Kitts & Nevis'      code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'St Helena'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Sri Lanka'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Spain'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'South Sudan'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Korea, Republic of'     code = 'KR'     rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'South Georgia/Sandwich Islands'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'South Africa'   code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Somalia'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Solomon Islands'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Slovenia'   code = ''   rating = 'Mid Term-BB ; Short Term-Medium'     isactive = 'Yes' )
 ( country = 'Slovakia'   code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Singapore'      code = ''   rating = 'Mid Term-AA ; Short Term-Medium'     isactive = 'Yes' )
 ( country = 'Sierra Leone'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Seychelles'     code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Serbia'     code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Senegal'    code = ''   rating = 'Mid Term-C ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Saudi Arabia'   code = 'SA'     rating = 'Mid Term-BB , Short Term-Medium'     isactive = 'Yes' )
 ( country = 'Sao Tome & Principe'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'San Marino'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Samoa'      code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Rwanda'     code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Russian Federation'         rating = 'Mid Term-C Short Term-Sensitive'     isactive = 'Yes' )
 ( country = 'Romania'    code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Reunion'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Qatar'      code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Puerto Rico'    code = ''   rating = 'Mid Term-BB ; Short Term-Sensitive'  isactive = 'Yes' )
 ( country = 'Portugal'   code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Poland'     code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Pitcairn Islands'   code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Philippines'    code = ''   rating = 'Mid Term-B ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Peru'   code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Paraguay'   code = ''   rating = 'Mid Term-C ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Papua New Guinea'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Panama'     code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Palau'      code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Pakistan'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Oman'   code = ''   rating = 'Mid Term-BB ; Short Term-Medium'     isactive = 'Yes' )
 ( country = 'Norway'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Northern Mariana Islands'   code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'North Korea'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Norfolk Island'     code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Niue'   code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Nigeria'    code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Niger'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Nicaragua'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'New Zealand'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'New Caledonia'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Netherlands'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Nepal'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Nauru'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Namibia'    code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Myanmar'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Mozambique'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Morocco'    code = ''   rating = 'Mid Term-B ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Montserrat'     code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Montenegro'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Mongolia'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Monaco'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Moldova'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Micronesia'     code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Mexico'     code = ''   rating = 'Mid Term-BB ; Short Term-Medium'     isactive = 'Yes' )
 ( country = 'Mayotte'    code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Mauritius'      code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Mauritania'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Martinique'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Marshall Islands'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Malta'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Mali'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Maldives'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Malaysia'   code = ''   rating = 'Mid Term-BB ; Short Term-Medium'     isactive = 'Yes' )
 ( country = 'Malawi'     code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Madagascar'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Macedonia, The Former Yugoslav Republic of'     code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Macao'      code = ''   rating = 'Mid Term-BB ; Short Term-Medium'     isactive = 'Yes' )
 ( country = 'Luxembourg'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Lithuania'      code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Liechtenstein'      code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Libya'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Liberia'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Lesotho'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Lebanon'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Latvia'     code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Laos'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Kyrgyzstan'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Kuwait'     code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Kiribati'   code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Kenya'      code = ''   rating = 'Mid Term-C ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Kazakhstan'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Jordan'     code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Japan'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Jamaica'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Italy'      code = ''   rating = 'Mid Term-A ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Israel'     code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Ireland'    code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Iraq'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Iran, Islamic Republic of'          rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Indonesia'      code = ''   rating = 'Mid Term-B ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'India'      code = ''   rating = 'Mid Term-B ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Iceland'    code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Hungary'    code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Hong Kong'      code = ''   rating = 'Mid Term-A ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Honduras'   code = ''   rating = 'Mid Term-C ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Heard and McDonald Islands'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Haiti'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Guyana'     code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Guinea-Bissau'          rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Guinea (Rep Of)'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Guatemala'      code = ''   rating = 'Mid Term-B ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Guam'   code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Guadeloupe'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Grenada'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Greenland'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Greece'     code = ''   rating = 'Mid Term-B ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Gibraltar'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Ghana'      code = ''   rating = 'Mid Term-B ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Germany'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Georgia'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Gambia'     code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Gabon'      code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'French Southern Territory'      code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'French Polynesia'   code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'French Guiana'      code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'France'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Finland'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Fiji'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Faroe Islands'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Falkland Islands'   code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Ethiopia'   code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Estonia'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Eritrea'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Equatorial Guinea'      code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'El Salvador'    code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Egypt'      code = ''   rating = 'Mid Term-C ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Ecuador'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Dominican Republic'     code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Dominica'   code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Djibouti'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Denmark'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Czech Republic'     code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Cyprus'     code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Curacao'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Cuba'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Croatia'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Côte d Ivoire'      code = ''   rating = 'Mid Term-C ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Costa Rica'     code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Cook Islands'   code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Congo (Peoples Rep Of)'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Congo, The Democratic Republic of the'          rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Comoros'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Colombia'   code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Cocos (Keeling) Islands'    code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Christmas Island'   code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'China'      code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Chile'      code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Chad'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Central African Republic'   code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Cayman Islands'     code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Cape Verde Islands'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Canada'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Cameroon'   code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Cambodia'   code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Burundi'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Burkina Faso'   code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Bulgaria'   code = ''   rating = 'Mid Term-B ; Short Term-Medium'  isactive = 'Yes' )
 ( country = 'Brunei'     code = ''   rating = 'Mid Term-BB ; Short Term-Medium'     isactive = 'Yes' )
 ( country = 'British Virgin Islands'     code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'British Indian Ocean Territory'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Brazil'     code = ''   rating = 'Mid Term-B ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Bouvet Island'      code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Botswana'   code = ''   rating = 'Mid Term-B ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Bosnia and Herzegovina'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Bolivia'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Bhutan'     code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'BES Islands (Bonaire, St Eustatius, Saba)'      code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Bermuda'    code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Benin'      code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Belize'     code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Belgium'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Belarus'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Barbados'   code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Bangladesh'     code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Bahrain'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Bahamas'    code = ''   rating = 'Mid Term-BB ; Short Term-Medium'     isactive = 'Yes' )
 ( country = 'Azerbaijan'     code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Austria'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Australia'      code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Aruba'      code = ''   rating = 'Mid Term-B ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Armenia'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )
 ( country = 'Argentina'      code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Antigua & Barbuda'      code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Antarctica'     code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Anguilla'   code = ''   rating = 'Mid Term-BB ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'Angola'     code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Andorra'    code = ''   rating = 'Mid Term-AA ; Short Term-Low'    isactive = 'Yes' )
 ( country = 'American Samoa'     code = ''   rating = 'Mid Term-A ; Short Term-Low'     isactive = 'Yes' )
 ( country = 'Algeria'    code = ''   rating = 'Mid Term-C ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Albania'    code = ''   rating = 'Mid Term-D ; Short Term-Sensitive'   isactive = 'Yes' )
 ( country = 'Afghanistan'    code = ''   rating = 'Mid Term-D ; Short Term-High'    isactive = 'Yes' )



).

*   delete existing entries in the database table
    DELETE FROM ztab_country.

*   insert the new table entries
    INSERT ztab_country FROM TABLE @itab.

*   output the result as a console message
    out->write( |{ sy-dbcnt } country entries inserted successfully!| ).
    ENDMETHOD.
ENDCLASS.
