CLASS zcl_layout_fields DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
      INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAYOUT_FIELDS IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

    DATA itab TYPE TABLE OF ztab_layout_fld.

* fill internal travel table (itab)
    itab = VALUE #(
   ( field_no = '1'     field_name = 'Change Request ID'     layout_no = '1' )
( field_no = '2'    field_name = 'Description'   layout_no = '1' )
( field_no = '3'    field_name = 'Priority'      layout_no = '1' )
( field_no = '4'    field_name = 'Due Date'      layout_no = '1' )
( field_no = '5'    field_name = 'Reason'    layout_no = '1' )
( field_no = '6'    field_name = 'Status'    layout_no = '1' )
( field_no = '7'    field_name = 'Current Workitem'      layout_no = '1' )
( field_no = '8'    field_name = 'Created On'     layout_no = '1' )
( field_no = '9'    field_name = 'Created By'     layout_no = '1' )
( field_no = '10'    field_name = 'Changed On'     layout_no = '1' )
( field_no = '11'    field_name = 'Changed By'     layout_no = '1' )
( field_no = '12'   field_name = 'Finalized On'   layout_no = '1' )
( field_no = '13'   field_name = 'Finalized By'   layout_no = '1' )
( field_no = '14'   field_name = 'Note'      layout_no = '1' )
( field_no = '15'   field_name = 'File'     layout_no = '2' )
( field_no = '16'   field_name = 'Link'     layout_no = '2' )
( field_no = '17'   field_name = 'Business Partner ID  Grouping'    layout_no = '3' )
( field_no = '18'   field_name = 'Title'     layout_no = '3' )
( field_no = '19'   field_name = 'Name'      layout_no = '3' )
( field_no = '20'   field_name = 'Name 2'    layout_no = '3' )
( field_no = '21'   field_name = 'Salutation'    layout_no = '3' )
( field_no = '22'   field_name = 'Search Term 1'     layout_no = '3' )
( field_no = '23'   field_name = 'Street'     layout_no = '3' )
( field_no = '24'   field_name = 'House Number'     layout_no = '3' )
( field_no = '25'   field_name = 'Postal Code'    layout_no = '3' )
( field_no = '26'   field_name = 'City'    layout_no = '3' )
( field_no = '27'   field_name = 'Country'   layout_no = '3' )
( field_no = '28'   field_name = 'State'      layout_no = '3' )
( field_no = '29'   field_name = 'Region'      layout_no = '3' )
( field_no = '30'   field_name = 'Language'      layout_no = '3' )
( field_no = '31'   field_name = 'Transportation Zone'   layout_no = '3' )
( field_no = '32'   field_name = 'PO Box Postal Code'   layout_no = '3' )
( field_no = '33'   field_name = 'PO Box'   layout_no = '3' )
( field_no = '34'   field_name = 'PO BOX Without Number'     layout_no = '3' )
( field_no = '35'   field_name = 'Company Postal Code'   layout_no = '3' )
( field_no = '36'   field_name = 'Legal Entity'      layout_no = '3' )
( field_no = '37'   field_name = 'Legal Form'    layout_no = '3' )
( field_no = '38'   field_name = 'Date Founded'      layout_no = '3' )
( field_no = '39'   field_name = 'Liquidation Date'      layout_no = '3' )
( field_no = '40'   field_name = 'Authorization Group'   layout_no = '3' )
( field_no = '41'   field_name = 'PO Box'    layout_no = '3' )
( field_no = '42'   field_name = 'Telephone Country'    layout_no = '3' )
( field_no = '43'   field_name = 'Telephone Number '    layout_no = '3' )
( field_no = '44'   field_name = 'Telephone Extension '    layout_no = '3' )
( field_no = '45'   field_name = 'Mobile '   layout_no = '3' )
( field_no = '46'   field_name = 'Fax Country '      layout_no = '3' )
( field_no = '47'   field_name = 'Fax Number '      layout_no = '3' )
( field_no = '48'   field_name = 'Fax Extension'      layout_no = '3' )
( field_no = '49'   field_name = 'Email'     layout_no = '3' )
( field_no = '50'   field_name = 'Website'   layout_no = '3' )
( field_no = '51'   field_name = 'BP role FLCU01'      layout_no = '4' )
( field_no = '52'   field_name = 'BP role FLCU00'      layout_no = '4' )
( field_no = '53'   field_name = 'BP role UKM000'      layout_no = '4' )
( field_no = '54'   field_name = 'BP role FLCU01'      layout_no = '4' )
( field_no = '55'   field_name = 'Address Version'   layout_no = '5' )
( field_no = '56'   field_name = 'Title'     layout_no = '5' )
( field_no = '57'   field_name = 'Name'      layout_no = '5' )
( field_no = '58'   field_name = 'Name 2'    layout_no = '5' )
( field_no = '59'   field_name = 'Search Term'   layout_no = '5' )
( field_no = '60'   field_name = 'Street'   layout_no = '5' )
( field_no = '61'   field_name = 'House Number'   layout_no = '5' )
( field_no = '62'   field_name = 'City'      layout_no = '5' )
( field_no = '63'   field_name = 'Address Type'      layout_no = '6' )
( field_no = '64'   field_name = 'Address'   layout_no = '6' )
( field_no = '65'   field_name = 'Standard Usage'    layout_no = '6' )
( field_no = '66'   field_name = 'ID'    layout_no = '7' )
( field_no = '67'   field_name = 'Bank Country'      layout_no = '7' )
( field_no = '68'   field_name = 'Bank Key'      layout_no = '7' )
( field_no = '69'   field_name = 'Bank Name'     layout_no = '7' )
( field_no = '70'   field_name = 'Bank Account'      layout_no = '7' )
( field_no = '71'   field_name = 'Account Name'      layout_no = '7' )
( field_no = '72'   field_name = 'Identification Type'      layout_no = '8' )
( field_no = '73'   field_name = 'Identification Number'    layout_no = '8' )
( field_no = '74'   field_name = 'Valid from date'   layout_no = '8' )
( field_no = '75'   field_name = 'Valid to date'     layout_no = '8' )
( field_no = '76'   field_name = 'Resonsible Institute'      layout_no = '8' )
( field_no = '77'   field_name = 'Entry Date'    layout_no = '8' )
( field_no = '78'   field_name = 'Country'   layout_no = '8' )
( field_no = '79'   field_name = 'Region'    layout_no = '8' )
( field_no = '80'   field_name = 'Tax Number Category'      layout_no = '9' )
( field_no = '81'   field_name = 'Tax Description'   layout_no = '9' )
( field_no = '82'   field_name = 'Tax Number'   layout_no = '9' )
( field_no = '83'   field_name = 'Industry'      layout_no = '10' )
( field_no = '84'   field_name = 'Industry Description'      layout_no = '10' )
( field_no = '85'   field_name = 'Standard Industry'     layout_no = '10' )
( field_no = '86'   field_name = 'Company Code'     layout_no = '11' )
( field_no = '87'   field_name = 'Reconciliation Account'   layout_no = '11' )
( field_no = '88'   field_name = 'Head Office'   layout_no = '11' )
( field_no = '89'   field_name = 'Authorization Group'   layout_no = '11' )
( field_no = '90'   field_name = 'Value Adjustment'      layout_no = '11' )
( field_no = '91'   field_name = 'Sort Key'      layout_no = '11' )
( field_no = '92'   field_name = 'Planning Group'    layout_no = '11' )
( field_no = '93'   field_name = 'Release Group'     layout_no = '11' )
( field_no = '94'   field_name = 'Interest Indicator'    layout_no = '11' )
( field_no = '95'   field_name = 'Interest Calculation Frequency'    layout_no = '11' )
( field_no = '96'   field_name = 'Last Key Date'     layout_no = '11' )
( field_no = '97'   field_name = 'Last Interest Run'     layout_no = '11' )
( field_no = '98'   field_name = 'Previous Account Number'   layout_no = '11' )
( field_no = '99'   field_name = 'Buying Group'      layout_no = '11' )
( field_no = '100'   field_name = 'Personnel Number'      layout_no = '11' )
( field_no = '101'   field_name = 'Terms Of Payment'      layout_no = '11' )
( field_no = '102'   field_name = 'Payment History Record'    layout_no = '11' )
( field_no = '103'   field_name = 'Credit Memo Payment Terms'     layout_no = '11' )
( field_no = '104'   field_name = 'B E Charges Payment Term'      layout_no = '11' )
( field_no = '105'   field_name = 'Check Cashing Time'    layout_no = '11' )
( field_no = '106'   field_name = 'Tolerance Group'   layout_no = '11' )
( field_no = '107'   field_name = 'Know Negotiated Leave'     layout_no = '11' )
( field_no = '108'   field_name = 'AR Pledging Indicator'     layout_no = '11' )
( field_no = '109'   field_name = 'Payment History Record'    layout_no = '11' )
( field_no = '110'   field_name = 'Payment Method'    layout_no = '11' )
( field_no = '111'   field_name = 'Alternative Payer'     layout_no = '11' )
( field_no = '112'   field_name = 'Bill Of Exchange Limit'    layout_no = '11' )
( field_no = '113'  field_name = 'Payment Method Supplement'     layout_no = '11' )
( field_no = '114'  field_name = 'Next Payee'    layout_no = '11' )
( field_no = '115'  field_name = 'Lockbox'   layout_no = '11' )
( field_no = '116'  field_name = 'Payment Block'     layout_no = '11' )
( field_no = '117'  field_name = 'House Bank'    layout_no = '11' )
( field_no = '118'  field_name = 'Grouping Key'      layout_no = '11' )
( field_no = '119'  field_name = 'Individual Payment'    layout_no = '11' )
( field_no = '120'  field_name = 'Payment Advice by EDI'     layout_no = '11' )
( field_no = '121'  field_name = 'Reason Code Conversion'    layout_no = '11' )
( field_no = '122'  field_name = 'Selection Rule'    layout_no = '11' )
( field_no = '123'  field_name = 'Policy Number'     layout_no = '11' )
( field_no = '124'  field_name = 'Amount Insured'    layout_no = '11' )
( field_no = '125'  field_name = 'Lead Months'   layout_no = '11' )
( field_no = '126'  field_name = 'Institute Number'      layout_no = '11' )
( field_no = '127'  field_name = 'Valid to'      layout_no = '11' )
( field_no = '128'  field_name = 'Deductible'    layout_no = '11' )
( field_no = '129'  field_name = 'Accounting Clerk'      layout_no = '11' )
( field_no = '130'  field_name = 'Account With Number'   layout_no = '11' )
( field_no = '131'  field_name = 'Account Memo'      layout_no = '11' )
( field_no = '132'  field_name = 'Clerk At Customer'     layout_no = '11' )
( field_no = '133'  field_name = 'Clerk Telephone Number'      layout_no = '11' )
( field_no = '134'  field_name = 'Account Statement'     layout_no = '11' )
( field_no = '135'  field_name = 'Collective Invoice Variant'    layout_no = '11' )
( field_no = '136'  field_name = 'Local Processing'      layout_no = '11' )
( field_no = '137'  field_name = 'Clerks Internet Address'      layout_no = '11' )
( field_no = '138'  field_name = 'Clerks Fax Number'    layout_no = '11' )
( field_no = '139'  field_name = 'Grouping Key'      layout_no = '11' )
( field_no = '140'  field_name = 'Dunning Area'      layout_no = '11' )
( field_no = '141'  field_name = 'Dunning Area Description'      layout_no = '11' )
( field_no = '142'  field_name = 'Withholding Tax Type'      layout_no = '11' )
( field_no = '143'  field_name = 'Withholding Tax Type Description'      layout_no = '11' )
( field_no = '144'  field_name = 'Customer with CI'    layout_no = '11' )
( field_no = '145'  field_name = 'Sales'     layout_no = '11' )
( field_no = '146'  field_name = 'Legal Deparment'   layout_no = '11' )
( field_no = '147'  field_name = 'Customer without CI'     layout_no = '11' )
( field_no = '148'  field_name = 'Accounting'    layout_no = '11' )
( field_no = '149'  field_name = 'Sales Organization'   layout_no = '12' )
( field_no = '150'  field_name = 'Distribution Channel'     layout_no = '12' )
( field_no = '151'  field_name = 'Division'     layout_no = '12' )
( field_no = '152'  field_name = 'Sales district'    layout_no = '12' )
( field_no = '153'  field_name = 'Sales Office'      layout_no = '12' )
( field_no = '154'  field_name = 'Sales Group'   layout_no = '12' )
( field_no = '155'  field_name = 'Customer Group'    layout_no = '12' )
( field_no = '156'  field_name = 'ABC Class'     layout_no = '12' )
( field_no = '157'  field_name = 'Currency'      layout_no = '12' )
( field_no = '158'  field_name = 'Account at Customer'   layout_no = '12' )
( field_no = '159'  field_name = 'Switch Off Rounding'   layout_no = '12' )
( field_no = '160'  field_name = 'Order Probability'     layout_no = '12' )
( field_no = '161'  field_name = 'Authorization Group'   layout_no = '12' )
( field_no = '162'  field_name = 'Item Proposal'     layout_no = '12' )
( field_no = '163'  field_name = 'Unit Of Measure Group'     layout_no = '12' )
( field_no = '164'  field_name = 'Exchange Rate Type'    layout_no = '12' )
( field_no = '165'  field_name = 'PP Customer Procedure'     layout_no = '12' )
( field_no = '166'  field_name = 'Price Group'   layout_no = '12' )
( field_no = '167'  field_name = 'Price list'    layout_no = '12' )
( field_no = '168'  field_name = 'Price Procedure Dterm.'    layout_no = '12' )
( field_no = '169'  field_name = 'Customer Statistics Group'     layout_no = '12' )
( field_no = '170'  field_name = 'Agency Business'   layout_no = '12' )
( field_no = '171'  field_name = 'Document Index Active'     layout_no = '12' )
( field_no = '172'  field_name = 'Delivery Priority'     layout_no = '12' )
( field_no = '173'  field_name = 'Shipping Conditions'   layout_no = '12' )
( field_no = '174'  field_name = 'Delivery Plant'    layout_no = '12' )
( field_no = '175'  field_name = 'Order Combination'     layout_no = '12' )
( field_no = '176'  field_name = 'Relevant POD'      layout_no = '12' )
( field_no = '177'  field_name = 'POD Timeframe'     layout_no = '12' )
( field_no = '178'  field_name = 'Complete Delivery'     layout_no = '12' )
( field_no = '179'  field_name = 'Maximum Number of Part. Deliveries'    layout_no = '12' )
( field_no = '180'  field_name = 'Partial Delivery per Item'     layout_no = '12' )
( field_no = '181'  field_name = 'Unlimited Tolerance'   layout_no = '12' )
( field_no = '182'  field_name = 'Underdelivery Tolerance'   layout_no = '12' )
( field_no = '183'  field_name = 'Overdelivery Tolerance'    layout_no = '12' )
( field_no = '184'  field_name = 'Manual Invoice Maintenance'    layout_no = '12' )
( field_no = '185'  field_name = 'Rebate'    layout_no = '12' )
( field_no = '186'  field_name = 'Pricing'   layout_no = '12' )
( field_no = '187'  field_name = 'Invoicing Dates'   layout_no = '12' )
( field_no = '188'  field_name = 'Invoicing List Dates'      layout_no = '12' )
( field_no = '189'  field_name = 'Incoterms'     layout_no = '12' )
( field_no = '190'  field_name = 'Inco. Location1'   layout_no = '12' )
( field_no = '191'  field_name = 'Payment Terms'     layout_no = '12' )
( field_no = '192'  field_name = 'Credit Control  Area'      layout_no = '12' )
( field_no = '193'  field_name = 'Payment Gurantee Procedure'    layout_no = '12' )
( field_no = '194'  field_name = 'Settlement Group'      layout_no = '12' )
( field_no = '195'  field_name = 'Account Assignment Group'      layout_no = '12' )
( field_no = '196'  field_name = 'Customer Group 1'      layout_no = '12' )
( field_no = '197'  field_name = 'Customer Group 2'      layout_no = '12' )
( field_no = '198'  field_name = 'Customer Group 3'      layout_no = '12' )
( field_no = '199'  field_name = 'Customer Group 4'      layout_no = '12' )
( field_no = '200'  field_name = 'Customer Group 5'      layout_no = '12' )
( field_no = '201'  field_name = 'Bill to Ship to Payer Buyer'   layout_no = '12' )
( field_no = '202'  field_name = 'Only Ship To'      layout_no = '12' )
( field_no = '203'  field_name = 'Sales Person'      layout_no = '12' )
( field_no = '204'  field_name = 'Agent'     layout_no = '12' )
( field_no = '205'  field_name = 'Country'      layout_no = '12' )
( field_no = '206'  field_name = 'Tax Category'      layout_no = '12' )
( field_no = '207'  field_name = 'Tax classification'    layout_no = '12' )
( field_no = '208'  field_name = 'Tax Category 2'    layout_no = '12' )
( field_no = '209'  field_name = 'Tax classification 2'      layout_no = '12' )
( field_no = '210'  field_name = 'Reason'    layout_no = '13' )
( field_no = '211'  field_name = 'Standard'      layout_no = '13' )
( field_no = '212'  field_name = 'Address'   layout_no = '13' )
( field_no = '213'  field_name = 'Authorization Group'   layout_no = '13' )
( field_no = '214'  field_name = 'Grouping Key'      layout_no = '13' )
( field_no = '215'  field_name = 'Trading Partner'   layout_no = '13' )
( field_no = '216'  field_name = 'ERP Customer'      layout_no = '13' )
( field_no = '217'  field_name = 'Account Group'     layout_no = '13' )
( field_no = '218'  field_name = 'Express Station'   layout_no = '13' )
( field_no = '219'  field_name = 'Train Station'     layout_no = '13' )
( field_no = '220'  field_name = 'Location Code'     layout_no = '13' )
( field_no = '221'  field_name = 'City Code'     layout_no = '14' )
( field_no = '222'  field_name = 'Country Code'      layout_no = '14' )
( field_no = '223'  field_name = 'Fiscal Address'    layout_no = '14' )
( field_no = '224'  field_name = 'Tax Type'      layout_no = '14' )
( field_no = '225'  field_name = 'Subtrip Group'     layout_no = '14' )
( field_no = '226'  field_name = 'Type of Business'      layout_no = '14' )
( field_no = '227'  field_name = 'Representative Name'     layout_no = '14' )
( field_no = '228'  field_name = 'Liable for VAT'    layout_no = '14' )
( field_no = '229'  field_name = 'Sales Equalization Tax'    layout_no = '14' )
( field_no = '230'  field_name = 'ICMS-Exempt'   layout_no = '14' )
( field_no = '231'  field_name = 'IPI-Exempt'    layout_no = '14' )
( field_no = '232'  field_name = 'CFOP Category'     layout_no = '14' )
( field_no = '233'  field_name = 'Type of Industry'      layout_no = '14' )
( field_no = '234'  field_name = 'DME Indicator'     layout_no = '15' )
( field_no = '235'  field_name = 'Instruction Key'   layout_no = '15' )
( field_no = '236'  field_name = 'Alernative Payer in Document'      layout_no = '15' )
( field_no = '237'  field_name = 'Alternative Payer'     layout_no = '15' )
( field_no = '238'  field_name = 'Nieson Indicator'      layout_no = '16' )
( field_no = '239'  field_name = 'Customer Classification'   layout_no = '16' )
( field_no = '240'  field_name = 'Industry Code 1'   layout_no = '16' )
( field_no = '241'  field_name = 'Industry Code 2'   layout_no = '16' )
( field_no = '242'  field_name = 'Industry Code 3'   layout_no = '16' )
( field_no = '243'  field_name = 'Industry Code 4'   layout_no = '16' )
( field_no = '244'  field_name = 'Industry Code 5'   layout_no = '16' )
( field_no = '245'  field_name = 'Industry Code 6'   layout_no = '16' )
( field_no = '246'  field_name = 'Industry Code 7'   layout_no = '16' )
( field_no = '247'  field_name = 'Annual Sales Currency'   layout_no = '17' )
( field_no = '248'  field_name = 'Sales Area'    layout_no = '16' )
( field_no = '249'  field_name = 'Empolyees'     layout_no = '16' )
( field_no = '250'  field_name = 'Fiscal Year Varaint'   layout_no = '16' )
( field_no = '251'  field_name = 'Biochemical Warfare'   layout_no = '17' )
( field_no = '252'  field_name = 'Nuclear Nonproliferation'      layout_no = '17' )
( field_no = '253'  field_name = 'National Security'     layout_no = '17' )
( field_no = '254'  field_name = 'Missile Technology'    layout_no = '17' )
( field_no = '255'  field_name = 'Non Miltary Use'   layout_no = '17' )
( field_no = '256'  field_name = 'Miltry Use'    layout_no = '17' )
( field_no = '257'  field_name = 'Attribute 1'   layout_no = '18' )
( field_no = '258'  field_name = 'Attribute 2'   layout_no = '18' )
( field_no = '259'  field_name = 'Attribute 3'   layout_no = '18' )
( field_no = '260'  field_name = 'Attribute 4'   layout_no = '18' )
( field_no = '261'  field_name = 'Attribute 5'   layout_no = '18' )
( field_no = '262'  field_name = 'Attribute 6'   layout_no = '18' )
( field_no = '263'  field_name = 'Attribute 7'   layout_no = '18' )
( field_no = '264'  field_name = 'Attribute 8'   layout_no = '18' )
( field_no = '265'  field_name = 'Attribute 9'   layout_no = '18' )
( field_no = '266'  field_name = 'Attribute 10'      layout_no = '18' )
( field_no = '267'  field_name = 'Condition Group 1'     layout_no = '18' )
( field_no = '268'  field_name = 'Condition Group 2'     layout_no = '18' )
( field_no = '269'  field_name = 'Condition Group 3'     layout_no = '18' )
( field_no = '270'  field_name = 'Condition Group 4'     layout_no = '18' )
( field_no = '271'  field_name = 'Condition Group 5'     layout_no = '18' )
( field_no = '272'  field_name = 'Document Type'     layout_no = '19' )
( field_no = '273'  field_name = 'Storage Category'      layout_no = '19' )
( field_no = '274'  field_name = 'Application'   layout_no = '19' )
( field_no = '275'  field_name = 'Description'   layout_no = '19' )
( field_no = '276'  field_name = 'Rule'      layout_no = '20' )
( field_no = '277'  field_name = 'Risk Class'    layout_no = '20' )
( field_no = '278'  field_name = 'Check rule'    layout_no = '20' )
( field_no = '279'  field_name = 'Credit Segment'    layout_no = '21' )
( field_no = '280'  field_name = 'Limit define'      layout_no = '21' )
( field_no = '281'  field_name = 'Limit'     layout_no = '21' )
( field_no = '282'  field_name = 'Validity to'   layout_no = '21' )
( field_no = '283'  field_name = 'Credit Segment'    layout_no = '22' )
( field_no = '284'  field_name = 'Relationship to BP'    layout_no = '22' )
( field_no = '285'   field_name = 'Initiator name '  layout_no = '23' )
( field_no = '286'   field_name = 'Business Unit '   layout_no = '23' )
( field_no = '287'   field_name = 'Vertical '    layout_no = '23' )
( field_no = '288'   field_name = 'Customer Group '  layout_no = '24' )
( field_no = '289'   field_name = 'Legal Name '  layout_no = '24' )
( field_no = '290'   field_name = 'Search Term'  layout_no = '24' )
( field_no = '291'   field_name = 'Add Ship to'  layout_no = '24' )
( field_no = '292'   field_name = 'BP Role'  layout_no = '24' )
( field_no = '293'   field_name = 'Year of Establishment '   layout_no = '24' )
( field_no = '294'   field_name = 'Type of Entity '  layout_no = '24' )
( field_no = '295'   field_name = 'Customer Internal Rating '    layout_no = '24' )
( field_no = '296'   field_name = 'Customer Type '   layout_no = '25' )
( field_no = '297'   field_name = 'Channel Group '   layout_no = '25' )
( field_no = '298'   field_name = 'Channel '     layout_no = '25' )
( field_no = '299'   field_name = 'Sub-Channel '    layout_no = '25' )
( field_no = '300'   field_name = 'Lineof Business Type '    layout_no = '25' )
( field_no = '301'   field_name = 'Country '     layout_no = '26' )
( field_no = '302'   field_name = 'Address Line 1 '  layout_no = '26' )
( field_no = '303'   field_name = 'Address Line 2 '  layout_no = '26' )
( field_no = '304'   field_name = 'Alternate Address '   layout_no = '26' )
( field_no = '305'   field_name = 'City '    layout_no = '26' )
( field_no = '306'   field_name = 'State '   layout_no = '26' )
( field_no = '307'   field_name = 'PO Box No-Pin code '  layout_no = '26' )
( field_no = '308'   field_name = 'Provins '     layout_no = '26' )
( field_no = '309'   field_name = 'Sub Area '    layout_no = '26' )
( field_no = '310'   field_name = 'Emirate '     layout_no = '26' )
( field_no = '311'   field_name = 'Paste In All'     layout_no = '26' )
( field_no = '312'   field_name = 'Proposed Background of Customer '     layout_no = '26' )
( field_no = '313'   field_name = 'Transportation Zone'  layout_no = '27' )
( field_no = '314'   field_name = 'First Name '  layout_no = '27' )
( field_no = '315'   field_name = 'Last Name '   layout_no = '27' )
( field_no = '316'   field_name = 'Designation '     layout_no = '27' )
( field_no = '317'   field_name = 'Email ID '    layout_no = '27' )
( field_no = '318'   field_name = 'Office Phone Number '     layout_no = '27' )
( field_no = '319'   field_name = 'Mobile No '   layout_no = '27' )
( field_no = '320'   field_name = 'VAT-GST No '  layout_no = '28' )
( field_no = '321'   field_name = 'Attachment VAT-GST No Attachment)'  layout_no = '28' )
( field_no = '322'   field_name = 'License Type '    layout_no = '28' )
( field_no = '323'   field_name = 'License No '  layout_no = '28' )
( field_no = '324'   field_name = 'License Attachment mandatory'   layout_no = '28' )
( field_no = '325'   field_name = 'Valid From '  layout_no = '28' )
( field_no = '326'   field_name = 'Valid To '    layout_no = '28' )
( field_no = '327'   field_name = 'Import License Number '   layout_no = '28' )
( field_no = '328'   field_name = 'Attachment Import License Number '  layout_no = '28' )
( field_no = '329'   field_name = 'Source of Enquiry '   layout_no = '28' )
( field_no = '330'   field_name = 'Partnership identity by-Pass '    layout_no = '29' )
( field_no = '331'   field_name = 'Partnership deed '    layout_no = '29' )
( field_no = '332'   field_name = 'Sponsors Passport '   layout_no = '29' )
( field_no = '333'   field_name = 'Commercial License '  layout_no = '29' )
( field_no = '334'   field_name = 'Company identity by-Pass '    layout_no = '30' )
( field_no = '335'   field_name = 'Owners Identity-pass '   layout_no = '30' )
( field_no = '336'   field_name = 'Certifications of Incorporation '     layout_no = '30' )
( field_no = '337'   field_name = 'Memorandum and articles of associations '     layout_no = '30' )
( field_no = '338'   field_name = 'Passport Copy '   layout_no = '30' )
( field_no = '339'   field_name = 'Valid Passport Date '     layout_no = '30' )
( field_no = '340'   field_name = 'Sponsors Passport '   layout_no = '30' )
( field_no = '341'   field_name = 'Commercial License '  layout_no = '30' )
( field_no = '342'   field_name = 'Visa Copy '   layout_no = '30' )
( field_no = '343'   field_name = 'Valid Visa Date '     layout_no = '30' )
( field_no = '344'   field_name = 'Route audit is performed '   layout_no = '30' )
( field_no = '345'   field_name = 'National ID Card '    layout_no = '30' )
( field_no = '346'   field_name = 'Document authenticated by chamber of commerce '   layout_no = '30' )
( field_no = '347'   field_name = 'Route code '  layout_no = '30' )
( field_no = '348'   field_name = 'KYC Form attachments with signature '     layout_no = '30' )
( field_no = '349'   field_name = 'Latitude '    layout_no = '30' )
( field_no = '350'   field_name = 'Longitude '   layout_no = '30' )
( field_no = '351'   field_name = 'Credit limit Currency '   layout_no = '31' )
( field_no = '352'   field_name = 'Credit Limit Type '   layout_no = '31' )
( field_no = '353'   field_name = 'Credit Limit Proposed Credit Limit Type '     layout_no = '31' )
( field_no = '354'   field_name = 'Business Proposal '  layout_no = '32' )
( field_no = '355'   field_name = 'Attachement'  layout_no = '32' )
( field_no = '356'   field_name = 'Rationable for Trading '  layout_no = '33' )
( field_no = '357'   field_name = 'Monthly Physical Buy Volume '     layout_no = '34' )
( field_no = '358'   field_name = 'Monthly Physical Sell Volume '    layout_no = '34' )
( field_no = '359'   field_name = 'Gross Average GC or avg gc-MT  '   layout_no = '35' )
( field_no = '360'   field_name = 'Avg GC-MT or GC '    layout_no = '35' )
( field_no = '361'   field_name = 'Inco Term '   layout_no = '35' )
( field_no = '362'   field_name = 'Monthly Paper Volume '    layout_no = '34' )
( field_no = '363'   field_name = 'Open Credit-Clean credit Amount '     layout_no = '36' )
( field_no = '364'   field_name = 'CAD amount '  layout_no = '36' )
( field_no = '365'   field_name = 'PDC in Hand amount '  layout_no = '36' )
( field_no = '366'   field_name = 'Undated Cheque-Security Deposit Cheque '  layout_no = '36' )
( field_no = '367'   field_name = 'Insurer '     layout_no = '36' )
( field_no = '368'   field_name = 'CRI Amount '  layout_no = '36' )
( field_no = '369'   field_name = 'Unconfirmed LC from non-Approved bank Name '  layout_no = '36' )
( field_no = '370'   field_name = 'Unconfirmed LC from non-Approved bank amount '    layout_no = '36' )
( field_no = '371'   field_name = 'Open Credit - Clean Credit Amount SAR'     layout_no = '36' )
( field_no = '372'   field_name = 'CAD Amount SAR'     layout_no = '36' )
( field_no = '373'   field_name = 'PDC in hand Amount SAR'     layout_no = '36' )
( field_no = '374'   field_name = 'Undated Cheque - Security Deposit Cheque Amount SAR'    layout_no = '36' )
( field_no = '375'   field_name = 'CRI only Insolvency risk Insurer'   layout_no = '36' )
( field_no = '376'   field_name = 'Insurer Amount SAR'    layout_no = '36' )
( field_no = '377'   field_name = 'Unconfirmed LC from Non-Approved Bank  Name'  layout_no = '36' )
( field_no = '378'   field_name = 'Unconfirmed LC from Non-Approved Bank Amount SAR'   layout_no = '36' )
( field_no = '379'   field_name = 'Debtors Balance of the customer as at last month end'    layout_no = '36' )
( field_no = '380'   field_name = 'Open Credit - Clean Credit Proposed Amount AED'    layout_no = '36' )
( field_no = '381'   field_name = 'Open Credit - Clean Credit Variance in Amount AED'    layout_no = '36' )
( field_no = '382'   field_name = 'CAD Amount AED'    layout_no = '36' )
( field_no = '383'   field_name = 'CAD Proposed Amount AED'    layout_no = '36' )
( field_no = '384'   field_name = 'CAD Variance in Amount AED'    layout_no = '36' )
( field_no = '385'   field_name = 'PDC in hand Amount AED'    layout_no = '36' )
( field_no = '386'   field_name = 'PDC in hand Proposed Amount AED'    layout_no = '36' )
( field_no = '387'   field_name = 'PDC in hand Variance in Amount AED'    layout_no = '36' )
( field_no = '388'   field_name = 'Undated Cheque - Security Deposit Cheque Amount AED'    layout_no = '36' )
( field_no = '389'   field_name = 'Undated Cheque - Security Deposit Cheque Proposed Amount AED'    layout_no = '36' )
( field_no = '390'   field_name = 'Undated Cheque - Security Deposit Cheque Variance in Amount AED'    layout_no = '36' )
( field_no = '391'   field_name = 'CRI Proposed Insurer'    layout_no = '36' )
( field_no = '392'   field_name = 'CRI Proposed Amount AED'    layout_no = '36' )
( field_no = '393'   field_name = 'CRI Variance in Amount AED'    layout_no = '36' )
( field_no = '394'   field_name = 'Unconfirmed LC from Non-Approved Bank Proposed Bank Name'    layout_no = '36' )
( field_no = '395'   field_name = 'Unconfirmed LC from Non-Approved Bank Proposed Amount AED'    layout_no = '36' )
( field_no = '396'   field_name = 'Unconfirmed LC from Non-Approved Bank Variance in Amount AED'    layout_no = '36' )
( field_no = '397'   field_name = 'Credit Limit Validity Proposed Date'    layout_no = '36' )
( field_no = '398'   field_name = 'Payment Terms Proposed Max. Credit Days'    layout_no = '36' )
( field_no = '399'   field_name = 'Payment Terms Proposed Payment Term'    layout_no = '36' )
( field_no = '400'   field_name = 'Stoploss - MT if any '     layout_no = '34' )
( field_no = '401'   field_name = 'Total Secured Credit Limit '  layout_no = '37' )
( field_no = '402'   field_name = 'Total Unsecured Credit Limit '    layout_no = '37' )
( field_no = '403'   field_name = 'Total Credit Amount '     layout_no = '37' )
( field_no = '404'   field_name = 'In Functional Currency '  layout_no = '37' )
( field_no = '405'   field_name = 'Proposed Total Secured Credit Limit AED'    layout_no = '37' )
( field_no = '406'   field_name = 'Total Secured Credit Limit Variance in Amount AED'     layout_no = '37' )
( field_no = '407'   field_name = 'Proposed Total Unsecured Credit Limit AED'  layout_no = '37' )
( field_no = '408'   field_name = 'Total Unsecured Credit Limit Variance in Amount AED'     layout_no = '37' )
( field_no = '409'   field_name = 'Proposed Credit Amount AED '    layout_no = '37' )
( field_no = '410'   field_name = 'Credit Variance in Amount AED'     layout_no = '37' )
( field_no = '411'   field_name = 'Proposed Date'    layout_no = '37' )
( field_no = '412'   field_name = 'Date '    layout_no = '38' )
( field_no = '413'   field_name = 'Proposed Max. Credit Days '   layout_no = '38' )
( field_no = '414'   field_name = 'Max Credit Days '     layout_no = '39' )
( field_no = '415'   field_name = 'Cash Collection '     layout_no = '39' )
( field_no = '416'   field_name = 'Transit Time '    layout_no = '39' )
( field_no = '417'   field_name = 'Total Credit Days '   layout_no = '39' )
( field_no = '418'   field_name = 'Is Proxima '  layout_no = '39' )
( field_no = '419'   field_name = 'Payment Terms '   layout_no = '39' )
( field_no = '420'   field_name = 'Proposed Payment Term '   layout_no = '39' )
( field_no = '421'   field_name = 'BU Name '     layout_no = '40' )
( field_no = '422'   field_name = 'BU Code '     layout_no = '40' )
( field_no = '423'   field_name = 'Site Name '   layout_no = '40' )
( field_no = '424'   field_name = 'Party Site No '   layout_no = '40' )
( field_no = '425'   field_name = 'Credit Limit '    layout_no = '40' )
( field_no = '426'   field_name = 'Balance Amt '     layout_no = '40' )
( field_no = '427'   field_name = 'Total Site Level Credit Limit '   layout_no = '40' )
( field_no = '428'   field_name = 'Total Credit Limit '  layout_no = '40' )
( field_no = '429'   field_name = 'Financial Statement '     layout_no = '41' )
( field_no = '430'   field_name = 'D& B Report '     layout_no = '41' )
( field_no = '431'   field_name = 'Bank Statement-References '   layout_no = '41' )
( field_no = '432'   field_name = 'Last 12 months statements of accounts or other documents '    layout_no = '41' )
( field_no = '433'   field_name = 'Year of Financial  '  layout_no = '41' )
( field_no = '434'   field_name = 'Revenue Net Profit currency '    layout_no = '41' )
( field_no = '435'   field_name = 'Revenue turn over '  layout_no = '41' )
( field_no = '436'   field_name = 'Net Profit '  layout_no = '41' )
( field_no = '437'   field_name = 'Country '     layout_no = '41' )
( field_no = '438'   field_name = 'Country Rating '  layout_no = '41' )
( field_no = '439'   field_name = 'D and B credit Rating '   layout_no = '41' )
( field_no = '440'   field_name = 'Irrevocable Bank Guarantee Bank Name '    layout_no = '43' )
( field_no = '441'   field_name = 'Irrevocable Bank Guarantee Bank Amount AED '    layout_no = '43' )
( field_no = '442'   field_name = 'Irrevocable LC from Approved Bank LC Issuance Bank Country '  layout_no = '43' )
( field_no = '443'   field_name = 'Irrevocable LC from Approved Bank LC Issuance Bank '  layout_no = '43' )
( field_no = '444'   field_name = 'Irrevocable LC from Approved Bank Amount AED '  layout_no = '43' )
( field_no = '445'   field_name = 'Irrevocable Confirmed LC LC Confirming Bank Country'  layout_no = '43' )
( field_no = '446'   field_name = 'Irrevocable Confirmed LC LC Confirming Bank '     layout_no = '43' )
( field_no = '447'   field_name = 'Irrevocable Confirmed LC Amount AED '   layout_no = '43' )
( field_no = '448'   field_name = 'Credit Risk Insurance Insurer '   layout_no = '43' )
( field_no = '449'   field_name = 'Credit Risk Insurance Amount AED '  layout_no = '43' )
( field_no = '450'   field_name = 'Credit Risk Insurance CRI Buyer ID '  layout_no = '43' )
( field_no = '451'   field_name = 'Credit Risk Insurance Approval Mail Attachment '  layout_no = '43' )
( field_no = '452'   field_name = 'Name of Company '     layout_no = '43' )
( field_no = '453'   field_name = 'Amount AED '    layout_no = '43' )
( field_no = '454'   field_name = 'Cash Deposit - Advance Amount AED '   layout_no = '43' )
( field_no = '455'   field_name = 'Avalization Draft Bank Name'  layout_no = '43' )
( field_no = '456'   field_name = 'Avalization Draft Amount AED'   layout_no = '43' )
( field_no = '457'   field_name = 'Credit Limit Validity Date '  layout_no = '43' )
( field_no = '458'   field_name = 'Irrevocable Bank Guarantee Proposed Bank Name '   layout_no = '43' )
( field_no = '459'   field_name = 'Irrevocable Bank Guarantee Proposed Amount AED '    layout_no = '43' )
( field_no = '460'   field_name = 'Irrevocable Bank Guarantee Variance in Amount AED'  layout_no = '43' )
( field_no = '461'   field_name = 'Irrevocable Bank Guarantee Proposed LC Issuance Bank '    layout_no = '43' )
( field_no = '462'   field_name = 'Irrevocable LC from Approved Bank Proposed Amount AED '     layout_no = '43' )
( field_no = '463'   field_name = 'Irrevocable LC from Approved Bank Variance in Amount AED'   layout_no = '43' )
( field_no = '464'   field_name = 'Irrevocable LC from Approved Bank Proposed LC Confirming Bank '   layout_no = '43' )
( field_no = '465'   field_name = 'Irrevocable Confirmed LC Proposed Amount AED '  layout_no = '43' )
( field_no = '466'   field_name = 'Irrevocable Confirmed LC Variance in Amount AED'    layout_no = '43' )
( field_no = '467'   field_name = 'Irrevocable Confirmed LC Proposed Insurer '   layout_no = '43' )
( field_no = '468'   field_name = 'Credit Risk Insurance Proposed Amount AED '     layout_no = '43' )
( field_no = '469'   field_name = 'Credit Risk Insurance Variance in Amount AED'   layout_no = '43' )
( field_no = '470'   field_name = 'Credit Risk Insurance Proposed CRI Buyer ID '     layout_no = '43' )
( field_no = '471'   field_name = 'Credit Risk Insurance Proposed Approval Mail Attachment '     layout_no = '43' )
( field_no = '472'   field_name = 'Proposed Name of Company '    layout_no = '43' )
( field_no = '473'   field_name = 'Proposed Amount AED '   layout_no = '43' )
( field_no = '474'   field_name = 'Variance in Amount AED'     layout_no = '43' )
( field_no = '475'   field_name = 'Cash Deposite - Advance Proposed Amount AED '     layout_no = '43' )
( field_no = '476'   field_name = 'Cash Deposite-Advance Variance in Amount AED'   layout_no = '43' )
( field_no = '477'   field_name = 'Avalization Draft Proposed Bank Name '    layout_no = '43' )
( field_no = '478'   field_name = 'Avalization Draft Proposed Amount AED '     layout_no = '43' )
( field_no = '479'   field_name = 'Avalization Draft Variance in Amount AED'   layout_no = '43' )
( field_no = '480'   field_name = 'Credit Risk Insurance Proposed Insurer'   layout_no = '43' )
( field_no = '481'   field_name = 'Date '    layout_no = '42' )
( field_no = '482'   field_name = 'User '    layout_no = '42' )
( field_no = '483'   field_name = 'Role '    layout_no = '42' )
( field_no = '484'   field_name = 'Status '  layout_no = '42' )
( field_no = '485'   field_name = 'Total Credit Limit Approved '     layout_no = '42' )
( field_no = '486'   field_name = 'Max Credit Days '     layout_no = '42' )
( field_no = '487'   field_name = 'Version '     layout_no = '42' )
( field_no = '488'   field_name = 'Remarks '     layout_no = '42' )
( field_no = '489'   field_name = 'PerformanceOverdue if any '   layout_no = '44' )
( field_no = '490'   field_name = 'Performance Provision created if any '    layout_no = '44' )
( field_no = '491'   field_name = 'Number of times customer defaulted payment terms '    layout_no = '44' )
( field_no = '492'   field_name = 'Customer Assessment and other factors'    layout_no = '44' )
( field_no = '493'   field_name = 'If CRI - then CRI withdrawn - Reduced in last 12 months'   layout_no = '44' )
( field_no = '494'   field_name = 'Are the details for Credit Analysis available (For unsecured credit it is mandatory)'     layout_no = '44' )
( field_no = '495'   field_name = 'Proposed Business Proposal '  layout_no = '45' )
( field_no = '496'   field_name = 'Proposed Business Proposal Attachments'   layout_no = '45' )
( field_no = '497'   field_name = 'Proposed Volume '     layout_no = '45' )
( field_no = '498'   field_name = 'Variance in Amount'   layout_no = '46' )
( field_no = '499'   field_name = 'Actual Volume'    layout_no = '46' )
( field_no = '500'   field_name = 'Proposed Value '  layout_no = '46' )
( field_no = '501'   field_name = 'Variance in Amount'   layout_no = '46' )
( field_no = '502'   field_name = 'Actual Turnover'  layout_no = '46' )
( field_no = '503'   field_name = 'Actual Sales Volume '     layout_no = '46' )
( field_no = '504'   field_name = 'Unit volume'     layout_no = '46' )
( field_no = '505'   field_name = 'Value'     layout_no = '46' )
( field_no = '506'   field_name = 'Currency'     layout_no = '46' )
( field_no = '507'   field_name = 'Generate Sites'   layout_no = '41' )
( field_no = '508'   field_name = 'Variance in Amount'   layout_no = '47' )
( field_no = '509'   field_name = 'Actual Volume'    layout_no = '47' )
( field_no = '510'   field_name = 'Actual Sales Value '  layout_no = '47' )
( field_no = '511'   field_name = 'Variance in Amount'   layout_no = '47' )
( field_no = '512'   field_name = 'Actual Turnover'  layout_no = '47' )
( field_no = '513'   field_name = 'Proposed Avg. GC-MT or GC'  layout_no = '47' )
( field_no = '514'   field_name = 'Variance in Amount'   layout_no = '48' )
( field_no = '515'   field_name = 'Actual GC Earned'     layout_no = '48' )
( field_no = '516'   field_name = 'Proposed Inco Term'   layout_no = '48' )
( field_no = '517'   field_name = 'Avg GC-MT of GC'   layout_no = '48' )
( field_no = '518'   field_name = 'Inco Term'   layout_no = '48' )
( field_no = '519'   field_name = 'Customer Debtors Balance at Last Month End '  layout_no = '48' )
( field_no = '520'   field_name = 'Overdue if any '  layout_no = '49' )
( field_no = '521'   field_name = 'Prov. For Doubtful Debt '     layout_no = '49' )
( field_no = '522'   field_name = 'Cheque Bounce '   layout_no = '49' )
( field_no = '523'   field_name = 'Cases of Delayed Payments '   layout_no = '49' )
( field_no = '524'   field_name = 'Max Delay '   layout_no = '49' )
( field_no = '525'   field_name = 'Attachment of Statement of Accounts '     layout_no = '49' )

    ).




*   delete existing entries in the database table
    DELETE FROM ztab_layout_fld.

*   insert the new table entries
    INSERT ztab_layout_fld FROM TABLE @itab.

*   output the result as a console message
    out->write( |{ sy-dbcnt } Layout entries inserted successfully!| ).
    endmethod.
ENDCLASS.
