CLASS zcl_generate_bank DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_GENERATE_BANK IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

    DATA itab TYPE TABLE OF ztab_bank.

* fill internal travel table (itab)
    itab = VALUE #(
     ( bank = 'Allied Bank Limited' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'Askari Bank Limited' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'Habib Bank Limited' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'National Bank of Pakistan' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'United Bank Limited' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'MCB Bank Limited' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'Bank Al Habib' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'Standard Chartered Bank (Pakistan)' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'Bank Al Falah' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'Faysal Bank Limited' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'Dubai Islamic Bank Pakistan' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'Meezan Bank' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
     ( bank = 'Habib Metropolitan Bank Limited' country = 'Pakistan' isactive = 'Yes' isbank_with_condition = 'No' )
( bank = 'NIB Bank Ltd' country = 'Pakistan'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'Bank of Ayudhya'  country = 'Thailand'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'TMB Bank Public Company Ltd'  country = 'Thailand'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Krung thai Bank Public Company Ltd'   country = 'Thailand'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Siam commercial Bank Public Company Ltd'  country = 'Thailand'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Kasikorn Bank Public Company Ltd' country = 'Thailand'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Bank Public Company Ltd' country = 'Thailand'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'DEPFA Bank'   country = 'Ireland' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'KBC Bank Ireland' country = 'Ireland' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Ireland'  country = 'Ireland' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Allied Irish Banks'   country = 'Ireland' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Nanyang commercial bank'  country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Industrial & Comm l Bank of China (Asia) Ltd' country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'HSBC' country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Hang Seng Bank'   country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Dah Sing Bank'    country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Chong hing bank ltd'  country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Chiyu Banking Corporation Ltd'    country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'China Construction Bank Asia Corp Ltd'    country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'China CITIC Bank International Limited'   country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of East Asia Limited'    country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Communications Hong Kong Ltd' country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of China Hong Kong Ltd'  country = 'Hong Kong'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Noor Bank'    country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Habib Bank AG Zurich' country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'United Arab Bank' country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Union National Bank'  country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Sharjah Islamic Bank' country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Bank of Ras Al Khaimah'  country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Bank of Fujairah'    country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Mashreq Bank' country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'First Abu Dhabi Bank' country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Emirates National Bank of Dubai'  country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Emirates Islamic Bank'    country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Dubai Islamic Bank'   country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Commercial Bank of Dubai' country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Commercial Bank International'    country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Sharjah'  country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Al Masraf'    country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Al Hilal Bank'    country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ajman Bank'   country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Abu Dhabi Islamic Bank'   country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Abu Dhabi Commercial Bank'    country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Union Internationale des Banques' country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Union Bancaire pour le Commerce et l’Industrie'   country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Societe Tunisienne de Banques'    country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Nationale Agricole'    country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Internationale Arabe de Tunisie'   country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque de l’Habitat'  country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Attijari Bank'    country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'EBRD' country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank ABC Tunisia' country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Arab Tunisian Bank'   country = 'Tunisia' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Sterling Bank'    country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Skye Bank'    country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'First City Monument Bank' country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Fidelity Bank'    country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Zenith Bank Plc'  country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'United Bank for Africa Plc'   country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Standard Chartered Bank Nigeria'  country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Stanbic IBTC Bank Plc'    country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Guaranty Trust Bank Plc'  country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'First Bank of Nigeria Ltd'    country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ecobank Nigeria Ltd'  country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Diamond Bank Plc' country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Citibank Nigeria' country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Access Bank Plc'  country = 'Nigeria' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'BCI - Fomento SA-BCI' country = 'Mozambique'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Standard Bank ,SARL'  country = 'Mozambique'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banco E Commercial De Mozambique' country = 'Mozambique'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banco International de Mocambique'    country = 'Mozambique'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'African Banking Corporation Mozambique'   country = 'Mozambique'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Export-Import Bank of Malaysia Berhad'    country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Standard Chartered Bank Malaysis Berhad'  country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Public Bank Berhad'   country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'OCBC Bank Malayan Berhad' country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Malayan Banking Berhad'   country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Kuwait Finance House Malayan Berhad'  country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Hong Leong Bank Berhad'   country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'CIMB Bank Berhad' country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Muamalat Malaysia Berhad'    country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Islam Malaysia'  country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ambank Berhad'    country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Alliance Bank'    country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Affin Bank Berhad'    country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Maybank Banking Berhad'   country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'HSBC Bank Malaysia Berhad'    country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'RHB Bank Berhad'  country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Africa Madagascar'    country = 'Madagascar'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'IBL Bank' country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Fransabank'   country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Credit Libanais'  country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Byblos Bank'  country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'BBAC' country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Libano Francaise'  country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bankmed'  country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Beirut'   country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'BLOM Bank s.a.l.' country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque du Liban-Bank of Lebanon'  country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Audi SAL'    country = 'Lebanon' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'The Co-Operative Bank of Kenya'   country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'PTA Bank' country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Prime Bank'   country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Equity Bank'  country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ecobank Kenya'    country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Chase Bank Kenya' country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Africa Kenya' country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Standard Chartered Bank Kenya'    country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'NIC Bank Limited' country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Kenya Commercial Bank LTD'    country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Investments & Mortgages Banks'    country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Equity Group Holdings Limits' country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Diamond Trust Bank Kenya Limited' country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Commercial Bank of Africa'    country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'CfC Stanbic Bank Limited (CSBL)'  country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Barclays Bank of Kenya Limited'   country = 'Kenya'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'PT Bank Pan Indonesia Tbk'    country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'PT. Bank Mega Tbk'    country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank UOB Buana'   country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Syariah Mandiri' country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Rakyat'  country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Resona Perdania' country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Permata' country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank OCBC Indonesia'  country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Nusantara Parahyangan'   country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Negara Indonesia'    country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Muamalat Indonesia'  country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Mizuho Indonesia'    country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Mandiri' country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank International Indonesia' country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank DBS Indonesia'   country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Danamon' country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Central Asia'    country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Bukopin' country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank BNP Paribas' country = 'Indonesia'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Zenith Bank Ghana'    country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Unibank Ghana'    country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Prudential Bank'  country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Guaranty Trust Bank'  country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ghana Commercial Bank'    country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Fidelity Bank'    country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ecobank Ghana'    country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Cal Bank' country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'SCB Ghana'    country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Ghana'    country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Agricultural Development Bank'    country = 'Ghana'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ecobank Gambia'   country = 'Gambia'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ecobank Gabon'    country = 'Gabon'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Internationale pour le Commerce et L’Industrie Du Gabon (BICIG)'   country = 'Gabon'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Gabonaise et Francaise Internationale' country = 'Gabon'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Du Caire'  country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Misr'  country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'QNB Al Ahli'  country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Bank of Egypt'   country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Commercial International Bank (Egypt) S.A.E.' country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Housing Bank' country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'NBK Egypt'    country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Arab Bank'    country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Alexandria'   country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'ENBD Egypt'   country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'NBAD' country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'HSBC Bank - Egypt S.A.E.' country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Barclays Bank - Egypt S.A.E.' country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Export-Import Bank of China - China Eximbank' country = 'China'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'China CITIC Bank Corporation Limited' country = 'China'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Agricultural Bank of China'   country = 'China'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'China Merchants Bank' country = 'China'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Communications'   country = 'China'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'China Construction Bank'  country = 'China'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of China'    country = 'China'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'ICBC' country = 'China'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Sonali Bank'  country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Janata Bank'  country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Agrani Bank'  country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'United Commercial Bank Limited'   country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'South East Bank Limited'  country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Pubali Bank Limited'  country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Prime Bank Limited'   country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Credit and Commerce Bank Limited'    country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Bank Limited'    country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Islami Bank Bangladesh Limited'   country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Export Import Bank of Bangladesh  Limited (Exim Bank)'    country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Eastern Bank Limited' country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Dutch Bangla Bank'    country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'City Bank Limited'    country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'BRAC Bank Ltd'    country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Asia Limited'    country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Al Arafah islamic Bank Limited'   country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'AB Bank Ltd'  country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of New York Mellon Corporation'  country = 'United States'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of America, National Association'    country = 'United States'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Wells Fargo & Company'    country = 'United States'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Citigroup Inc'    country = 'United States'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'JPMorgan Chase & Co'  country = 'United States'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Alternatifbank A.S.'  country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Sekerbank T.A.S.' country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Turkiye Finans Katilim Bankasi AS'    country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Kuveyt Turk Katilim Bankasi A.S.-Kuwait Turkish Participation Bank Inc'   country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'HSBC Bank A.S.'   country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'ING Bank A.S.'    country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Turk Ekonomi Bankasi A.S.'    country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Finansbank A.S.'  country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Denizbank A.S.'   country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Turkiye Halk Bankasi A.S.'    country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Turkiye Vakiflar Bankasi TAO' country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Yapi Ve Kredi Bankasi A.S.'   country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Akbank T.A.S.'    country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Turkiye Garanti Bankasi A.S.' country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'T.C. Ziraat Bankasi A.S.' country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Turkiye is Bankasi A.S. - ISBANK' country = 'Turkey'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'ABC International Bank Plc'   country = 'United Kingdom'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Santander UK Group Holdings Plc'  country = 'United Kingdom'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Standard Chartered Plc'   country = 'United Kingdom'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Lloyds Banking Group Plc' country = 'United Kingdom'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Royal Bank of Scotland Group Plc (The)'   country = 'United Kingdom'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Barclays Bank Plc'    country = 'United Kingdom'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'HSBC Holdings Plc'    country = 'United Kingdom'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Development Bank Plc-NDB Bank'   country = 'Sri Lanka'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Sampath Bank Plc' country = 'Sri Lanka'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Hatton National Bank Plc' country = 'Sri Lanka'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Commercial Bank of Ceylon Plc'    country = 'Sri Lanka'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Peoples Bank'    country = 'Sri Lanka'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Ceylon'   country = 'Sri Lanka'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Africa - Senegal' country = 'Senegal' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ecobank Senegal'  country = 'Senegal' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Société Générale de Banques au Sénégal'   country = 'Senegal' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Security Bank Corporation'    country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Union Bank of the Philippines'    country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Rizal Commercial Banking Corp.'   country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Development Bank of the Philippines'  country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'China Banking Corporation - Chinabank'    country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Philippine National Bank' country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Land Bank of the Philippines' country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of The Philippine Islands'   country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Metropolitan Bank & Trust Company'    country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'BDO Unibank Inc'  country = 'Philippines' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'SBI (Mauritius) Ltd'  country = 'Mauritius'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'AfrAsia Bank Ltd' country = 'Mauritius'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Barclays Bank Mauritius Limited'  country = 'Mauritius'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Mauritius Commercial Bank Ltd (The)'  country = 'Mauritius'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Gulf Bank Kuwait' country = 'Kuwait'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Industrial Bank of Kuwait K.S.C.' country = 'Kuwait'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Boubyan Bank KSCP'    country = 'Kuwait'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Al Ahli Bank of Kuwait (KSC)' country = 'Kuwait'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ahli United Bank KSC' country = 'Kuwait'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Commercial Bank of Kuwait K.P.S.C. (The)' country = 'Kuwait'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Burgan Bank SAK'  country = 'Kuwait'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Kuwait Finance House' country = 'Kuwait'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Bank of Kuwait S.A.K.'   country = 'Kuwait'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Canadian Imperial Bank of Commerce CIBC'  country = 'Canada'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'HSBC Bank Canada' country = 'Canada'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Bank of Canada'  country = 'Canada'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Montreal' country = 'Canada'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Nova Scotia'  country = 'Canada'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Toronto Dominion Bank'    country = 'Canada'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Royal Bank of Canada' country = 'Canada'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Bank of Bahrain' country = 'Bahrain' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Commercial Bank (The)'   country = 'Bahrain' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'BBK B.S.C.'   country = 'Bahrain' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Gulf International Bank BSC'  country = 'Bahrain' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Arab Banking Corporation BSC-Bank ABC'    country = 'Bahrain' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ahli United Bank BSC' country = 'Bahrain' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Standard Bank of South Africa Ltd.'   country = 'South Africa'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Investec Limited' country = 'South Africa'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Nedbank Group Limited'    country = 'South Africa'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Absa Bank Ltd'    country = 'South Africa'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'FirstRand Limited'    country = 'South Africa'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Standard Bank Group Limited'  country = 'South Africa'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Arab Petroleum Investments Corporation - APICORP' country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank AlBilad' country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Al-Jazira JSC'   country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Islamic Development Bank' country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Saudi Investment Bank (The)'  country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Saudi Hollandi Bank (Alawwal bank)'   country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Saudi British Bank JSC (The)' country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Saudi Fransi JSC'  country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Gulf International Bank Dhahran branch'   country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'JP Morgan Riyadh Branch'  country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Riyad Bank'   country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Samba Financial Group'    country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Al Rajhi Bank Public Joint Stock Company' country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Commercial Bank (The)'   country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'UCO Bank' country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Oriental Bank of Commerce Ltd.'   country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Indusind Bank Limited'    country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Indian Overseas Bank' country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Kotak Mahindra Bank Limited'  country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Andhra Bank'  country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Indian Bank'  country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Corporation Bank Ltd.'    country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Allahabad Bank'   country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Syndicate Bank'   country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Central Bank of India'    country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'IDBI Bank Ltd'    country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Union Bank of India'  country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'AXIS Bank Limited'    country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Canara Bank'  country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'HDFC Bank Ltd'    country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of India'    country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'HSBC India'   country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'SCB India'    country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Punjab National Bank' country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Baroda'   country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'ICICI Bank Limited'   country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'State Bank of India'  country = 'India'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Arab Banking Corporation (Jordan)'    country = 'Jordan'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Jordan Commercial Bank'   country = 'Jordan'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Capital Bank of Jordan'   country = 'Jordan'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank al Etihad'   country = 'Jordan'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Jordan Ahli Bank Plc' country = 'Jordan'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Jordan Kuwait Bank'   country = 'Jordan'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Jordan Islamic Bank'  country = 'Jordan'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Housing Bank for Trade & Finance (The)'   country = 'Jordan'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Arab Bank Plc'    country = 'Jordan'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ahli Bank SAOG'   country = 'Oman'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Oman Arab Bank SAOC'  country = 'Oman'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Sohar SAOG'  country = 'Oman'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'HSBC Bank Oman'   country = 'Oman'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'National Bank of Oman (SAOG)' country = 'Oman'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Dhofar SAOG' country = 'Oman'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank Muscat SAOG' country = 'Oman'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Crédit du Maroc'  country = 'Morocco' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Marocaine pour le Commerce et l Industrie BMCI'    country = 'Morocco' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Société Générale Marocaine de Banques'    country = 'Morocco' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Crédit Agricole du Maroc' country = 'Morocco' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Centrale Populaire SA' country = 'Morocco' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Banque Marocaine du Commerce Extérieur-BMCE Bank' country = 'Morocco' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Attijariwafa Bank'    country = 'Morocco' isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Debub Global Bank'    country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Abay Bank'    country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Commercial Bank of Ethiopia'  country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Zemen Bank'   country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Oromia International Bank Sc' country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'NIB International Bank S.C.'  country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Bank of Abyssinia'    country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Wegagen Bank S.C.'    country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'United Bank S.C.' country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Dashen Bank S.C.' country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Awash International Bank S.C.'    country = 'Ethiopia'    isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'International Bank of Qatar'  country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Commercial Bank of Qatar QSC/ CBQ Finance'    country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Ahli Bank QSC'    country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Barwa Bank'   country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Qatar International Islamic Bank' country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Al Khalij Commercial Bank'    country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Doha Bank'    country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Masraf Al Rayan (Q.S.C.)' country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Qatar Islamic Bank SAQ'   country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'The Commercial Bank (QSC)'    country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Qatar National Bank'  country = 'Qatar'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Invest Bank PSC'  country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'National Bank of Umm Al Quwain'   country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'National Bank of Abu Dhabi'   country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'First Gulf Bank'  country = 'United Arab Emirates'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'Standard Chartered Bank'  country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'Publi Bank Berhad'    country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'Hong Leong Bank'  country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'CIMB' country = 'Malaysia'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'African Export Import Bank'   country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Arab African International Bank'  country = 'Egypt'   isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'Export Import Bank of Bangladesh Limited (Exim Bank)' country = 'Bangladesh'  isactive = 'Yes'    isbank_with_condition = 'Yes' )
( bank = 'British Arab Commercial Bank' country = 'United Kingdom'  isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'Bank AlJazira JSC'    country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'Saudi Hollandi Bank'  country = 'Saudi Arabia'    isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'Vijaya Bank'  country = 'India'   isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'State Bank of Travancore' country = 'India'   isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'State Bank of Patiala'    country = 'India'   isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'State Bank of Mysore' country = 'India'   isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'State Bank of Hyderabad'  country = 'India'   isactive = 'Yes'    isbank_with_condition = 'No' )
( bank = 'State Bank of Bikaner and Jaipur' country = 'India'   isactive = 'Yes'    isbank_with_condition = 'No' )



     ).

*   delete existing entries in the database table
    DELETE FROM ztab_bank.

*   insert the new table entries
    INSERT ztab_bank FROM TABLE @itab.

*   output the result as a console message
    out->write( |{ sy-dbcnt } Bank entries inserted successfully!| ).

  ENDMETHOD.
ENDCLASS.
