CLASS zcl_generate_lineofbusns DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
        INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_GENERATE_LINEOFBUSNS IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

    DATA itab TYPE TABLE OF ztab_lineofbusns.

    itab = VALUE #(
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'LARGE_GROCERY'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTELS'   lineofbusinesstype = '2-3_STAR_HOTEL'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTELS'   lineofbusinesstype = '4-5_STAR_HOTEL'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'AIRLINE'  isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Animal Nutrition'     lineofbusinesstype = 'ANIMAL_NUTRITION'     isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CAFETERIA'    lineofbusinesstype = 'ARABIC_COFFEE_SHOPS'  isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Snacking'     lineofbusinesstype = 'BAKED_PRODUCTS_BISCUITS'  isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Snacking'     lineofbusinesstype = 'BAKED_PRODUCTS_SNACKS'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'Artisanal Bakeries'  subchannel = 'Craft Bakery'     lineofbusinesstype = 'BAKERY_SUB_DISTRIBUTOR'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'CONVENIENCE'  lineofbusinesstype = 'BRANDED_SUPERETTS'    isactive = 'Yes' )
( channelgroup = 'Iffco Sea'     channel = 'Iffco Sea'   subchannel = 'Food'     lineofbusinesstype = 'BULK_OIL_TRADING'     isactive = 'Yes' )
( channelgroup = 'Iffco Sea'     channel = 'Iffco Sea'   subchannel = 'Non Food'     lineofbusinesstype = 'BULK_OIL_TRADING'     isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CAFETERIA'    lineofbusinesstype = 'CAFETERIA'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CAFETERIA'    lineofbusinesstype = 'CAFETERIA_WHOLESALE'  isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Non_Food'    subchannel = 'Candles'  lineofbusinesstype = 'CANDLES'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'CATERING_WHOLESALER_SPECIALIST'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'CATERING_SPECIALIST'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'NGO'     subchannel = 'Charity'  lineofbusinesstype = 'Charity'  isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Dairy'    lineofbusinesstype = 'CHEESE'   isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Confectionary'    lineofbusinesstype = 'CHOCOLATE'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'LEISURE'  lineofbusinesstype = 'CINEMA'   isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Dairy'    lineofbusinesstype = 'COAGULATED_CHEESE'    isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Dairy'    lineofbusinesstype = 'CONDENSED_MILK'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'CONVENIENCE'  lineofbusinesstype = 'CONVENIENCE'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'Local Modern Trade'   lineofbusinesstype = 'COOP'     isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'CONVENIENCE'  lineofbusinesstype = 'CORNER_STORE'     isactive = 'Yes' )
( channelgroup = 'Packaging'     channel = 'Corrugated'  subchannel = 'Corrugated'   lineofbusinesstype = 'CORRUGATED'   isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Dairy'    lineofbusinesstype = 'CREAM'    isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Culinary'     lineofbusinesstype = 'CULINARY'     isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'SELF SERVICE'     lineofbusinesstype = 'DEPARTMENTAL_STORE'   isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Non_Food'    subchannel = 'Detergents'   lineofbusinesstype = 'DETERGENTS_&_SOAPS'   isactive = 'Yes' )
( channelgroup = 'Feed'  channel = 'Feed'    subchannel = 'Feed'     lineofbusinesstype = 'DIRECT_CONSUME'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'Distributor'  lineofbusinesstype = 'DISTRIBUTOR_'     isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'Artisanal Bakeries'  subchannel = 'Bakery Distributor'   lineofbusinesstype = 'DISTRIBUTOR'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'Local Modern Trade'   lineofbusinesstype = 'DUTY_FREE'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'EDUCATION'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'EVENT_CATERING'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'Pharmacy'     lineofbusinesstype = 'EXCLUSIVE_MEDICAL_STORE'  isactive = 'Yes' )
( channelgroup = 'Transport'     channel = 'Transport'   subchannel = 'External Transport'   lineofbusinesstype = 'EXTERNAL_CUSTOMER'    isactive = 'Yes' )
( channelgroup = 'Feed'  channel = 'Feed'    subchannel = 'Feed'     lineofbusinesstype = 'FARMS'    isactive = 'Yes' )
( channelgroup = 'Feed'  channel = 'Feed'    subchannel = 'Feed'     lineofbusinesstype = 'FEED_RETAIIL'     isactive = 'Yes' )
( channelgroup = 'Feed'  channel = 'Feed'    subchannel = 'Feed'     lineofbusinesstype = 'FEED_WHOLESALE'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'SELF SERVICE'     lineofbusinesstype = 'FORECOURT'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'GENERAL_STORE'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'NGO'     subchannel = 'Govt. Aid'    lineofbusinesstype = 'Govt. Aid'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'GOVT_ARMY_DPT'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'GOVT_JAIL_DPT'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'GOVT_POLICE_DPT'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'GOVT_SCHOOL_DPT'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'HABER_STORE'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'HEALTH_CARE'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTELS'   lineofbusinesstype = 'HOTELS_DISTRIBUTOR'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTEL RESTAURANTS'    lineofbusinesstype = 'HR_ LOCAL_CHAIN_WESTERN'  isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTEL RESTAURANTS'    lineofbusinesstype = 'HR_INDEPENDEN_ORIENTAL_AND_FAR_EAST'  isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTEL RESTAURANTS'    lineofbusinesstype = 'HR_INDEPENDENT_ARABIC'    isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTEL RESTAURANTS'    lineofbusinesstype = 'HR_INDEPENDENT_SOUTH_ASIAN'   isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTEL RESTAURANTS'    lineofbusinesstype = 'HR_INDEPENDENT_WESTERN'   isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTEL RESTAURANTS'    lineofbusinesstype = 'HR_LOCAL_CHAIN_ARABIC'    isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTEL RESTAURANTS'    lineofbusinesstype = 'HR_LOCAL_CHAIN_CAFÉ_RESTAURANT'   isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTEL RESTAURANTS'    lineofbusinesstype = 'HR_LOCAL_CHAIN_ORIENTAL_AND_FAR_EAST'     isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTEL RESTAURANTS'    lineofbusinesstype = 'HR_LOCAL_CHAIN_SOUTH_ASIAN'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'Local Modern Trade'   lineofbusinesstype = 'HYPER_MARKET'     isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'International Modern Trade'   lineofbusinesstype = 'HYPER MARKET'     isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Dairy'    lineofbusinesstype = 'ICE_CREAM'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'INDEPENDENT_ARABIC'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'INDEPENDENT_ORIENTAL_AND_FAR_EAST'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'INDEPENDENT_SOUTH_ASIAN'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'INDEPENDENT_WESTERN'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'Instore & Key Account'   subchannel = 'Industrial Bakery'    lineofbusinesstype = 'INDUSTRIAL_BAKERY'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'Instore & Key Account'   subchannel = 'Industrial Bakery'    lineofbusinesstype = 'INDUSTRIAL_BAKERY_SUB_DISTRIBUTOR'    isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Distributor'  lineofbusinesstype = 'INDUSTRIAL_DISTRIBUTOR'   isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Non_Food'    subchannel = 'Industrial Distributor Non Food'  lineofbusinesstype = 'INDUSTRIAL_DISTRIBUTOR_NON_FOOD'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'Instore & Key Account'   subchannel = 'Instore'  lineofbusinesstype = 'INSTORE_BAKERY'   isactive = 'Yes' )
( channelgroup = 'Intercompany'  channel = 'Intercompany'    subchannel = 'Intercompany'     lineofbusinesstype = 'INTERCOMPANY'     isactive = 'Yes' )
( channelgroup = 'Transport'     channel = 'Transport'   subchannel = 'Internal Transport'   lineofbusinesstype = 'INTERNAL_CUSTOMER'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'International Modern Trade'   lineofbusinesstype = 'INTERNATIONAL_CASH_N_CARRY'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'Others'   lineofbusinesstype = 'INTERNATIONAL_SALE'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'KEY_ACCOUNTS'     lineofbusinesstype = 'KA CASUAL_DINNING'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'KEY_ACCOUNTS'     lineofbusinesstype = 'KA COFFEE_SHOP'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'KEY_ACCOUNTS'     lineofbusinesstype = 'KA_MIXED_GROUP'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'KEY_ACCOUNTS'     lineofbusinesstype = 'KA_QSR'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'CONVENIENCE'  lineofbusinesstype = 'KIOSK'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'KIRYANA_STORE'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'LARGE_DUKA'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'LEISURE'  lineofbusinesstype = 'LICENSED TRADE'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'LOCAL'    lineofbusinesstype = 'LO_CASUAL_DINNING'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'LOCAL'    lineofbusinesstype = 'LO_COFFEE_SHOP'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'LOCAL'    lineofbusinesstype = 'LO_MIXED_GROUP'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'LOCAL'    lineofbusinesstype = 'LO_QSR'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'WHOLESALE'    lineofbusinesstype = 'LOCAL_CASH_N_CARRY'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'LOCAL_CHAIN_ARABIC'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'LOCAL_CHAIN_CAFE_RESTAURANT'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'LOCAL_CHAIN_ORIENTAL_AND_FAR_EAST'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'LOCAL_CHAIN_SOUTH_ASIAN'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'LOCAL_CHAIN_WESTERN'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'Local Modern Trade'   lineofbusinesstype = 'LOCAL_MODERN_TRADE'   isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'OFS Processors'   lineofbusinesstype = 'MARGARINE'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'Pharmacy'     lineofbusinesstype = 'MEDICAL_STORE'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'MEDIUM_GROCERY'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'CONVENIENCE'  lineofbusinesstype = 'MINI_MARKET'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Distributor'     subchannel = 'Modern Trade'     lineofbusinesstype = 'MODERN_TRADE'     isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'NGO'     subchannel = 'Non Govt. Aid'    lineofbusinesstype = 'Non Govt. Aid'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'OFFICES'  lineofbusinesstype = 'OFICE_CANTEEN'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTELS'   lineofbusinesstype = 'OTHERS_LODGINGS'  isactive = 'Yes' )
( channelgroup = 'Iffco Sea'     channel = 'Iffco Sea'   subchannel = 'Food'     lineofbusinesstype = 'PACKED_OIL_TRADING'   isactive = 'Yes' )
( channelgroup = 'Iffco Sea'     channel = 'Iffco Sea'   subchannel = 'Non Food'     lineofbusinesstype = 'PACKED_OIL_TRADING'   isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'OFS Processors'   lineofbusinesstype = 'PACKED_OILS'  isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Non_Food'    subchannel = 'Chemicals'    lineofbusinesstype = 'PAINT_RESINS'     isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'CONVENIENCE'  lineofbusinesstype = 'PAN_SHOP'     isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'LEISURE'  lineofbusinesstype = 'PARKS'    isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Pasta'    lineofbusinesstype = 'PASTA_MANUFACTURERS'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'CONVENIENCE'  lineofbusinesstype = 'PETROL_PUMP'  isactive = 'Yes' )
( channelgroup = 'Packaging'     channel = 'Plastic'     subchannel = 'Plastic'  lineofbusinesstype = 'PLASTIC'  isactive = 'Yes' )
( channelgroup = 'Private_Label'     channel = 'Private Label'   subchannel = 'Private Label'    lineofbusinesstype = 'PRIVATE_LABEL'    isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Meat'     lineofbusinesstype = 'PROCESSED_MEAT'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'RESTAURANTS'  lineofbusinesstype = 'RESTAURANT_WHOLESALER'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Distributor'     subchannel = 'Retail'   lineofbusinesstype = 'RETAIL'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'RURAL_INDEPENDENTS'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'Others'   lineofbusinesstype = 'SAMPLE_N_FOC'     isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CAFETERIA'    lineofbusinesstype = 'SCHOOL_CANTEEN_PRIVATE'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CAFETERIA'    lineofbusinesstype = 'SCHOOL_CANTEEN_PUBLIC'    isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Seasonings'   lineofbusinesstype = 'SEASONING_MANUFACTURERS'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'SELF SERVICE'     lineofbusinesstype = 'SELF_SERVICE'     isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'ARTISANAL_INSTORE_BAK'   subchannel = 'Semi - Industrial'    lineofbusinesstype = 'SEMI_AUTOMATED_BAKERY'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'WHOLESALE'    lineofbusinesstype = 'SEMI_WHOLESALE'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'SHIP_CHANDLING'   isactive = 'Yes' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'OFS Processors'   lineofbusinesstype = 'SHORTENING'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'SMALL_DUKA'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'SMALL_GROCERY'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'LEISURE'  lineofbusinesstype = 'SPA'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'STAFF_FEEDING'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'Artisanal Bakeries'  subchannel = 'Craft Bakery'     lineofbusinesstype = 'STAND_ALONE_CRAFT_BAKER'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'Local Modern Trade'   lineofbusinesstype = 'SUPER_MARKET'     isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'International Modern Trade'   lineofbusinesstype = 'SUPER_MARKET'     isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'TABLE_TOPS'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'Artisanal Bakeries'  subchannel = 'Tandoor'  lineofbusinesstype = '_TANDOOR_'    isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'Artisanal Bakeries'  subchannel = 'Tandoor'  lineofbusinesstype = 'TANDOOR_SUBDISTRIBUTOR'   isactive = 'No' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Confectionary'    lineofbusinesstype = 'TOFFEE_AND_CANDIES'   isactive = 'Yes' )
( channelgroup = 'Iffco Sea'     channel = 'Iffco Sea'   subchannel = 'Trading'  lineofbusinesstype = 'TRADING'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Distributor'     subchannel = 'Traditional Trade'    lineofbusinesstype = 'TRADITIONAL_TRADE'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'GROCERY'  lineofbusinesstype = 'URBAN_INDEPENTS'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'Others'   lineofbusinesstype = 'WALK_IN'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'WHOLESALE'    lineofbusinesstype = 'WHOLESALE'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Distributor'     subchannel = 'WHOLESALE'    lineofbusinesstype = 'WHOLESALE'    isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_MT'  subchannel = 'SELF SERVICE'     lineofbusinesstype = 'DS'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'SELF SERVICE'     lineofbusinesstype = 'SELF SERVICE'     isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'ARTISANAL_INSTORE_BAK'   subchannel = 'BAK_DISTRIBUTOR'  lineofbusinesstype = 'BAKERY_DISTRIBUTOR_L4'    isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'ARTISANAL_INSTORE_BAK'   subchannel = 'Craft Bakery'     lineofbusinesstype = 'BAKERY SUB-D'     isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'ARTISANAL_INSTORE_BAK'   subchannel = 'Craft Bakery'     lineofbusinesstype = 'STAND_ALONE_CRAFT_BAKERY'     isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'ARTISANAL_INSTORE_BAK'   subchannel = 'INDUSTRIAL_BAKERY_L3'     lineofbusinesstype = 'INDUSTRIAL_BAKERY_'   isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'ARTISANAL_INSTORE_BAK'   subchannel = 'INDUSTRIAL_BAKERY_L3'     lineofbusinesstype = 'IND_BAKERY SUB-D_'    isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'ARTISANAL_INSTORE_BAK'   subchannel = 'Instore'  lineofbusinesstype = 'INSTORE BAKERY_'  isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'TANDOOR_CH'  subchannel = 'Tandoor'  lineofbusinesstype = 'TANDOOR_'     isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'SELF SERVICE'     lineofbusinesstype = 'Departmental Store'   isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'ARTISANAL_INSTORE_BAK'   subchannel = 'BAK_DISTRIBUTOR'  lineofbusinesstype = 'Bakery Distributor'   isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'ARTISANAL_INSTORE_BAK'   subchannel = 'Craft Bakery'     lineofbusinesstype = 'Bakery Sub Distributor'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Distributor'     subchannel = 'WHOLESALE'    lineofbusinesstype = 'DISTRIBUTOR_WHOLESALE'    isactive = 'Yes' )
( channelgroup = 'Private_Label'     channel = 'PRIVATE_LABEL1'  subchannel = 'PRIVATE_LABEL2'   lineofbusinesstype = 'PRIVATE_LABEL3'   isactive = 'No' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'IND_DISTRIBUTOR'  lineofbusinesstype = 'IND_DISTRIBUTOR_'     isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'WHOLESALE'    lineofbusinesstype = 'WS'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Distributor'     subchannel = 'Modern Trade'     lineofbusinesstype = 'DISTRIBUTOR_MODERN TRADE'     isactive = 'Yes' )
( channelgroup = 'Feed'  channel = 'Feed'    subchannel = 'Feed'     lineofbusinesstype = 'FEED_RETAIL_LOC'  isactive = 'Yes' )
( channelgroup = 'Feed'  channel = 'Feed'    subchannel = 'Feed'     lineofbusinesstype = 'FARMS_LOC'    isactive = 'No' )
( channelgroup = 'Feed'  channel = 'Feed'    subchannel = 'Feed'     lineofbusinesstype = 'FEED_WS_LOC'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Distributor'     subchannel = 'Retail'   lineofbusinesstype = 'DISTRIBUTOR_RETAIL'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'INTERNATIONAL MT'     lineofbusinesstype = 'HM_INT'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'WHOLESALE'    lineofbusinesstype = 'SEMI_WS'  isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'IND_DIST_NONF'    lineofbusinesstype = 'IND_DIST_NONF_'   isactive = 'Yes' )
( channelgroup = 'Feed'  channel = 'FEED_LEV2'   subchannel = 'FEED_LEV3'    lineofbusinesstype = 'DIR_CONSUME_LOC'  isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Distributor'     subchannel = 'DT_TRADITIONAL TRADE'     lineofbusinesstype = 'DISTRIBUTOR_TRADITIONAL TRADE'    isactive = 'No' )
( channelgroup = 'OTHERS'    channel = 'Transport'   subchannel = 'External Transport'   lineofbusinesstype = 'EXTERNAL CUSTOMER'    isactive = 'No' )
( channelgroup = 'Intercompany'  channel = 'INTERCOMPANY_LEV2'   subchannel = 'INTERCOMPANY_LEV3'    lineofbusinesstype = 'INTERCOMPANY_LEV4'    isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'Others'   lineofbusinesstype = 'SAMPLE & FOC'     isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_TT'  subchannel = 'OTHERS_TT'    lineofbusinesstype = 'WALK-IN'  isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Modern Trade'    subchannel = 'Modern Trade'     lineofbusinesstype = 'HM_LCL'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_MT'  subchannel = 'LOCAL MT'     lineofbusinesstype = 'CO-OP'    isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_MT'  subchannel = 'LOCAL MT'     lineofbusinesstype = 'SM_LCL'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_TT'  subchannel = 'GROCERY'  lineofbusinesstype = 'GENERAL STORE'    isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CAFETERIA'    lineofbusinesstype = 'CAFETERIA_'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_TT'  subchannel = 'GROCERY'  lineofbusinesstype = 'MEDIUM GROCERY'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_TT'  subchannel = 'CONVENIENCE'  lineofbusinesstype = 'CONVENIENCE_'     isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'CATERING_WS_SPECIALIST'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_TT'  subchannel = 'GROCERY'  lineofbusinesstype = 'LG'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_TT'  subchannel = 'OTHERS_TT'    lineofbusinesstype = 'INT_SALE'     isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'CATERING'     lineofbusinesstype = 'SHIP CHANDLING'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_TT'  subchannel = 'CONVENIENCE'  lineofbusinesstype = 'PETPUMP'  isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'WHOLESALE'    lineofbusinesstype = 'LOCAL CASH N CARRY'   isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTELS'   lineofbusinesstype = '4-5 STAR HOTEL'   isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'CHAINS'  subchannel = 'CHAINS_DISTRIBUTOR'   lineofbusinesstype = 'BROADLINE_DISTRIBUTOR'    isactive = 'No' )
( channelgroup = 'Industrial'    channel = 'Non_Food'    subchannel = 'IND_DIST_NONF_'   lineofbusinesstype = 'IND_DIST_NONF'    isactive = 'Yes' )
( channelgroup = 'INDUSTRIES'    channel = 'Food'    subchannel = 'Dairy'    lineofbusinesstype = 'CONDENSED MILK'   isactive = 'No' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'HORECA'  subchannel = 'HOTELS'   lineofbusinesstype = 'HOTELS_DISTRIBUTOR_'  isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'LOC_TT'  subchannel = 'CONVENIENCE'  lineofbusinesstype = 'MINI MARKET'  isactive = 'No' )
( channelgroup = 'Packaging'     channel = 'CORRUGATED_LEV2'     subchannel = 'Craft Bakery'     lineofbusinesstype = 'CORRUGATED_LEV4'  isactive = 'No' )
( channelgroup = 'Packaging'     channel = 'PLASTICS_LEV2'   subchannel = 'PLASTICS_LEV3'    lineofbusinesstype = 'PLASTICS_LEV4'    isactive = 'No' )
( channelgroup = 'Industrial'    channel = 'Food'    subchannel = 'Dairy'    lineofbusinesstype = 'ICE CREAM'    isactive = 'Yes' )
( channelgroup = 'INDUSTRIES'    channel = 'Non_Food'    subchannel = 'Detergents'   lineofbusinesstype = 'DETERGENTS & SOAPS'   isactive = 'No' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Ecommerce BTOC'  subchannel = 'Ecommerce BTOC'   lineofbusinesstype = 'Generalist Pure Players'  isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Ecommerce BTOC'  subchannel = 'Ecommerce BTOC'   lineofbusinesstype = 'Food Pure Players'    isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'Ecommerce BTOB'  subchannel = 'Ecommerce BTOB'   lineofbusinesstype = 'Food Pure Players BTOB'   isactive = 'Yes' )
( channelgroup = 'IFFCO CONSUMER'    channel = 'Traditional Trade'   subchannel = 'Discounters'  lineofbusinesstype = 'Discounters'  isactive = 'Yes' )
( channelgroup = 'IFFCO PROFESSIONAL'    channel = 'TANDOOR_CH'  subchannel = 'Tandoor'  lineofbusinesstype = 'Tandoor Subdistributor'   isactive = 'Yes' )





    ).

*   delete existing entries in the database table
    DELETE FROM ztab_lineofbusns.

*   insert the new table entries
    INSERT ztab_lineofbusns FROM TABLE @itab.

*   output the result as a console message
    out->write( |{ sy-dbcnt } Line of Business entries inserted successfully!| ).


  ENDMETHOD.
ENDCLASS.
