CLASS zcl_generate_sales_head DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_generate_sales_head IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.
  DATA itab TYPE TABLE OF ztab_sales_head.
itab = VALUE #(

( reviewer =    'Sharepoint Admin'  revieweridemail =   'shareadmin@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mary Rose Lopez'   revieweridemail =   'mlopez@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Serhad Cemal Kelemci'  revieweridemail =   'skelemci@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Anil Prabhakar Sulay'  revieweridemail =   'asulay@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Manish Swarup' revieweridemail =   'mswarup@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Tariq Taiyab'  revieweridemail =   'ttaiyab@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Zubair siddiqui'   revieweridemail =   'zsiddiqui@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohammad Ahsanuddin'   revieweridemail =   'moahsanuddin@iffco.com'    saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'Peerzada syed Yousuf Pasha'    financerevieweremail =
'pyousuf@iffco.com' )
( reviewer =    'Vincent Dourado'   revieweridemail =   'vdourado@iffco.com'    saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'Peerzada syed Yousuf Pasha'    financerevieweremail =  'pyousuf@iffco.com' )
( reviewer =    'Basem fahmi Tawfiq mukbil' revieweridemail =   'btmukbil@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Muhammad Zaid Khalid'  revieweridemail =   'mkhalid@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Rizwan Ali Lakhani'    revieweridemail =   'rlakhani@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sarathy Iyyappan'  revieweridemail =   'siyyappan@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Vinit Nikhil Mehta'    revieweridemail =   'vimehta@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Adelene Waring'    revieweridemail =   'awaring@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Nisheeth Sanwal'   revieweridemail =   'nsanwal@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ashish D Trivedi'  revieweridemail =   'atrivedi@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Erattuparamal Ibrahim kutty salam' revieweridemail =   'ekutty@iffco.com'  saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Abbas Ahmed'   revieweridemail =   'abahmed@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Anas Aboonhi'  revieweridemail =   'aaboonhi@iffco.com'    saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'Peerzada syed Yousuf Pasha'    financerevieweremail =  'pyousuf@iffco.com' )
( reviewer =    'Rajamani Bhaskar'  revieweridemail =   'rbhaskar@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Muhammad Mehar Khawaja Munir'  revieweridemail =   'mmehar@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Souheil Ben Mansour'   revieweridemail =   'smansour@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mahmoud Serhan'    revieweridemail =   'mserhan@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Vinod Kanchan' revieweridemail =   'vkanchan@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sheeba Moby Philip'    revieweridemail =   'sphilip@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Avneet Singh'  revieweridemail =   'singha@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Rishi Kakkad'  revieweridemail =   'rkakkad@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Archita Shah'  revieweridemail =   'ashah@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Arshad Alam Khan'  revieweridemail =   'arskhan@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sanchali Gupta'    revieweridemail =   'sangupta@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Fadi Selwan'   revieweridemail =   'fselwan@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Jiju T K'  revieweridemail =   'jiju@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Surinder Bir Virk' revieweridemail =   'svirk@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Galina Vladimirovna Kholodova' revieweridemail =   'gkholodova@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Shaikh Parvez Ahmed'   revieweridemail =   'sparvez@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Masood Ul Ghani'   revieweridemail =   'maghani@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Yasir Khan'    revieweridemail =   'yakhan@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Kamal Rajani'  revieweridemail =   'krajani@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Khurram Fareed Khan'   revieweridemail =   'khkhan@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Khalid Abu Omar'   revieweridemail =   'komar@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Milad Albir Thabet'    revieweridemail =   'mthabet@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Muhammad Muzammil' revieweridemail =   'mumuzammil@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Dias Bosco'    revieweridemail =   'dbosco@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohammad Abdul Gabbar' revieweridemail =   'mgabbar@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohammad Rafeeque' revieweridemail =   'mrafeeque@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ankur Eusebius'    revieweridemail =   'aeusebius@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Abdul Gaffar'  revieweridemail =   'agaffar@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Rajin Kakkadan'    revieweridemail =   'rkakkadan@iffco.com'   saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Wong Siew Ling'    revieweridemail =   'slwong@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Fernando Alberto Arias'    revieweridemail =   'farias@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Muhammad Arshad Maroof'    revieweridemail =   'mmaroof@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Purnendu Thakore Rajeshwar'    revieweridemail =   'pthakore@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ibrahim Mamlouk'   revieweridemail =   'imamlouk@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Radha Krishnan'    revieweridemail =   'rkrishnan@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Thomas Samuel' revieweridemail =   'tsamuel@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Joaquim Martins'   revieweridemail =   'jmartins@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Imtiyaz Safruddin Shaikh'  revieweridemail =   'ishaikh@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohmed Altaf Surya'    revieweridemail =   'msurya@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Allan Benny'   revieweridemail =   'abenny@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Nirmal Palakkda Pushpan'   revieweridemail =   'npushpan@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'K Manoj'   revieweridemail =   'kmanoj@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Richard William Pattinson' revieweridemail =   'rpattinson@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'Himanshu Khanna'   financerevieweremail =  'HKHANNA@iffco.com' )
( reviewer =    'Anurag Sen'    revieweridemail =   'asen@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Komala Arumugam'   revieweridemail =   'karumugam@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Prakash Kumar' revieweridemail =   'prkumar@iffco.com' saleshead =     'Peerzada syed Yousuf Pasha'    salesheademail =    'pyousuf@iffco.com' financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Rosemarie Dela Cruz'   revieweridemail =   'rdcruz@iffco.com'  saleshead =     'Atia Abdul Wahab'  salesheademail =    'aabdulwa@iffco.com'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Santosh Sidharam Solse'    revieweridemail =   'sansolse@iffco.com'    saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'Peerzada syed Yousuf Pasha'    financerevieweremail =
'pyousuf@iffco.com' )
( reviewer =    'Subair Erath'  revieweridemail =   'serath@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ashish Agarwal'    revieweridemail =   'asagarwal@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sachin Gulati' revieweridemail =   'sgulati@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Santhosh Vatokke Puthukkott'   revieweridemail =   'sputhukkott@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Nishith Mehta' revieweridemail =   'nmehta@iffco.com'  saleshead =     'Sanjiv Mathur' salesheademail =    'smathur@iffco.com' financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Abdeltawab Azab'   revieweridemail =   'aasab@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Hamilton Gilbert'  revieweridemail =   'hgilbert@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Abdul Jabbar'  revieweridemail =   'ajabbar@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Aslam Nazeer Shaikh'   revieweridemail =   'saslam@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sp Test user 1'    revieweridemail =   'Spuser1@iffco.com' saleshead =     'Sp Test user 1'    salesheademail =    'Spuser1@iffco.com' financereviewer =   'Sp Test user 2'    financerevieweremail =  'Spuser2@iffco.com' )
( reviewer =    'Sp Test user 2'    revieweridemail =   'Spuser2@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sp Test user 3'    revieweridemail =   'Spuser3@iffco.com' saleshead =     'Sp Test user 1'    salesheademail =    'Spuser1@iffco.com' financereviewer =   'Sp Test user 3'    financerevieweremail =  'Spuser3@iffco.com' )
( reviewer =    'Asad Umair'    revieweridemail =   'aumair@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ashish Wadodkar'   revieweridemail =   'awadodkar@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Suhas Sudhakar Katkar' revieweridemail =   'skatkar@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohammad Asif Tajik'   revieweridemail =   'mtajik@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Muzammil Yasar'    revieweridemail =   'myasar@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Manoj Shriyan' revieweridemail =   'mshriyan@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohd. Abdul Gafoor'    revieweridemail =   'magafoor@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Muhammad Kashif Khan'  revieweridemail =   'mkashifkhan@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Gautam Kulbahadur Pradhan' revieweridemail =   'gpradhan@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Hemant Narbadashankar Trivedi' revieweridemail =   'htrivedi@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Samir Avdhut Prabhu'   revieweridemail =   'sprabhu@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'May Ann Desamito Gracio'   revieweridemail =   'mgracio@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Atul Bhatt'    revieweridemail =   'abhatt@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mario Moreira' revieweridemail =   'mmoreira@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Saurabh Daga'  revieweridemail =   'sdaga@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ashwin Pawar'  revieweridemail =   'appawar@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohammed Ibrahim Shaikh'   revieweridemail =   'mhshaikh@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Rashid Hamid'  revieweridemail =   'rhamid@iffco.com'  saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'Peerzada syed Yousuf Pasha'    financerevieweremail =  'pyousuf@iffco.com' )
( reviewer =    'Gulzar Ghazanfar'  revieweridemail =   'gghazanfar@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sana Bousseaden'   revieweridemail =   'sbousseaden@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ausaf Ahmed'   revieweridemail =   'auahmed@iffco.com' saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'Peerzada syed Yousuf Pasha'    financerevieweremail =  'pyousuf@iffco.com' )
( reviewer =    'Thomas Mark Alvares'   revieweridemail =   'talvares@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Kerim Ufuk Dal'    revieweridemail =   'kdal@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Salman Naweed' revieweridemail =   'snaweed@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Dawood Yasin Mukadam'  revieweridemail =   'dmukadam@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Hussam Ghanoum'    revieweridemail =   'hghanoum@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Abdul Wadood'  revieweridemail =   'awadood@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Rehan Saeed Khan'  revieweridemail =   'rsaeed@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohammed Ibrahim Shaikh'   revieweridemail =   'mohshaikh@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Soavelo Hary Nantenaina Toky'  revieweridemail =   'stoky@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Amir Norasyid Kamari'  revieweridemail =   'akamari@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Kiran Ramkrishna Ghule'    revieweridemail =   'kghule@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Amos Kiboi Gachuiga'   revieweridemail =   'akgachuiga@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mehreen Khudabux'  revieweridemail =   'mkhudabux@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Denzel Nicholas Heath' revieweridemail =   'dheath@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Farz Ahmad'    revieweridemail =   'faahmad@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Omar M. Adel'  revieweridemail =   'oadel@iffco.com'   saleshead =     'Himanshu Khanna'   salesheademail =    'HKHANNA@iffco.com' financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Norsam Bin Yusof'  revieweridemail =   'ynorsam@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Abdul Rahiman Mufid'   revieweridemail =   'amufid@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Anastasios Charitakis' revieweridemail =   'acharitakis@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Arshad Ahemad Khan'    revieweridemail =   'arkhan@iffco.com'  saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'Peerzada syed Yousuf Pasha'    financerevieweremail =  'pyousuf@iffco.com' )
( reviewer =    'Faizaan Aslam Khan'    revieweridemail =   'faikhan@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Shalain Abrol' revieweridemail =   'sabrol@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Clarice Relma De Pili' revieweridemail =   'cdepili@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Velson Salvador Jeronimo'  revieweridemail =   'vdias@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'AX Server' revieweridemail =   '_axserver@iffco1.onmicrosoft.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'MDM'   revieweridemail =   'mdm@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Bauddin Z Pathan'  revieweridemail =   'BPathan@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Syed Shafiqh Ahamed'   revieweridemail =   'sahamed@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Kapil Shankarlal Sharma'   revieweridemail =   'ksharma@iffco.com' saleshead =     'Kiran Ramkrishna Ghule'    salesheademail =    'kghule@iffco.com'  financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Zamri Kamal'   revieweridemail =   'zkamal@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Shahrukh Iqbal'    revieweridemail =   'siqbal@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Shahzad Rasheed'   revieweridemail =   'srasheed@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Awais Pasha'   revieweridemail =   'mpasha@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Shoaib Hussan' revieweridemail =   'shussan@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Zakaria Heikal'    revieweridemail =   'zheikal@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ahmed El Elami'    revieweridemail =   'aelelami@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Hesham Farouk' revieweridemail =   'Hfarouk@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sherif Mohamed Abdelkhalek'    revieweridemail =   'sabdelkhalek@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Riadh ben Salah'   revieweridemail =   'Rbensalah@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Tarek Gomaa'   revieweridemail =   'tgommaa@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Norhan Hassan' revieweridemail =   'nhassan@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohamed Ahmed Youssef' revieweridemail =   'myoussef@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Moez Zid'  revieweridemail =   'MZid@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Babar Hanif'   revieweridemail =   'bhanif@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Haris Ali Khan'    revieweridemail =   'hkhan@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Fahad Saleem'  revieweridemail =   'fahad@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Amal Khedr'    revieweridemail =   'AKhedr@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ahmad Irfan Butt'  revieweridemail =   'aibutt@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Nicolas Tan'   revieweridemail =   'twei@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'DAVIDE PARON'  revieweridemail =   'dparon@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohamed Abdulnaby Ghaly'   revieweridemail =   'Mghaly@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Usama Javed'   revieweridemail =   'ujaved@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Hammad Zahid'  revieweridemail =   'hzahid@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Nermin Adel Mohamed'   revieweridemail =   'namohamed@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Olubunmi Enoch Jalade' revieweridemail =   'ojalade@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Bambang Rukyanto'  revieweridemail =   'brukyanto@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Durachman' revieweridemail =   'Durachman@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Kamran Ahmed'  revieweridemail =   'Kaahmed@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Syed Sharique Anwar'   revieweridemail =   'sanwar@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Nermin Salman' revieweridemail =   'nsalman@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Jose Manuel Ramirez Sanchez'   revieweridemail =   'jsanchez@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Syed Nusrat Hassan'    revieweridemail =   'SHASSAN@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Kristy Jen Lazaga Generoso'    revieweridemail =   'kgeneroso@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Alaa Zouheir El Ferkh' revieweridemail =   'aelferkh@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Shaikh Khalid Ahmed'   revieweridemail =   'SKAHMED@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Gorjan Lalchevski' revieweridemail =   'GLALCHEVSKI@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Arslan Raza'   revieweridemail =   'arsraza@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Salam Sameer Abdaljalil'   revieweridemail =   'sabdaljalil@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Diana Mwende'  revieweridemail =   'dmwende@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mehmet Dogrul' revieweridemail =   'MDOGRUL@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Walid Ben Salah'   revieweridemail =   'wsalah@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sarra Khodja'  revieweridemail =   'skhodja@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Muhammad Hassan Siddiqui'  revieweridemail =   'MHSIDDIQUI@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Zorana Denic'  revieweridemail =   'zdenic@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Roger Heneine' revieweridemail =   'RHENEINE@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Garcia Makuiza'    revieweridemail =   'Gmakuiza@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Akash U Patel' revieweridemail =   'AUPATEL@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Muhammad Aamir'    revieweridemail =   'maamir@iffco.com'  saleshead =     'Mohd. Abdul Gafoor'    salesheademail =    'magafoor@iffco.com'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Syed Shafiq Ahmed' revieweridemail =   'syeahmed@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Dinesh Kumar'  revieweridemail =   'DKUMAR@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Walid Mamdouh Abdellatif'  revieweridemail =   'wmamdouh@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'John Mochia'   revieweridemail =   'jmochia@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Faizan Hamid'  revieweridemail =   'fhamid@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Omer Basoglu'  revieweridemail =   'OBASOGLU@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Moussa Saghir' revieweridemail =   'msaghir@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sujatha Ettickan'  revieweridemail =   'Settickan@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Michela Ferraro'   revieweridemail =   'mferraro@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Yigit Caglialtuncu'    revieweridemail =   'yigit@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ninan George'  revieweridemail =   'kgeorge@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Abdul Wadood Khan' revieweridemail =   'abdwadood@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Diwakar Jain'  revieweridemail =   'DJAIN@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sri Venkata Naga Sivakrishna Challapalli'  revieweridemail =   'SCHALLAPALLI@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ahmed Saad'    revieweridemail =   'agsaad@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Nur Sara Athirah Othman'   revieweridemail =   'NOTHMAN@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Kapil Kumar'   revieweridemail =   'KAPKUMAR@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Doaa Salah'    revieweridemail =   'dsalah@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sanjiv Mathur' revieweridemail =   'smathur@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Adel Hamada'   revieweridemail =   'ahamada@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Ahsan Iftikhar Khan'   revieweridemail =   'AIKHAN@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Uma Rani Nakka'    revieweridemail =   'UNAKKA@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Nikhil Gupta'  revieweridemail =   't_ngupta@iffco.com'    saleshead =     'Nikhil Gupta'  salesheademail =    't_ngupta@iffco.com'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Shafeeque Pallikkal'   revieweridemail =   'spallikkal@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Faisal Abid'   revieweridemail =   'FABID@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Tariq Abrar'   revieweridemail =   'tabrar@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Imran Haider'  revieweridemail =   'ihaider@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Pauline Salve Senoran' revieweridemail =   'psenoran@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Square Foko'   revieweridemail =   'SFOKO@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Shankar Chhipi'    revieweridemail =   'schhipi@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Jaroslaw Pietraszko'   revieweridemail =   'Jaroslaw@iffco1.onmicrosoft.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Antonio Guerreiro' revieweridemail =   'aguerreiro@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Amjad Ali Kazi'    revieweridemail =   'AKAZI@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Seshagiri Kotni'   revieweridemail =   'SKOTNI@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'SP Test User 4'    revieweridemail =   'spuser4@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'SP Test User 5'    revieweridemail =   'spuser5@iffco.com' saleshead =     'Sp Test user 2'    salesheademail =    'Spuser2@iffco.com' financereviewer =   'Sp Test user 2'    financerevieweremail =  'Spuser2@iffco.com' )
( reviewer =    'SP Test User 6'    revieweridemail =   'spuser6@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Javad Mohammed Khaleel'    revieweridemail =   'jmkhaleel@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Amr Ibrahim Sebak' revieweridemail =   'ASEBAK@iffco.com'  saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Hanif Abbas Shaikh'    revieweridemail =   'HSHAIKH@iffco.com' saleshead =     'Prakash Kumar' salesheademail =    'prkumar@iffco.com' financereviewer =   'Peerzada syed Yousuf Pasha'    financerevieweremail =  'pyousuf@iffco.com' )
( reviewer =    'Ali Sahad Mohammed'    revieweridemail =   'ASAHAD@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mohammad Ali Shirshi'  revieweridemail =   'mshirshi@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Elham Basheer Faiz Zuriky' revieweridemail =   'EZURIKY@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Dagmar Kulenova'   revieweridemail =   'DKULENOVA@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Osama Nageeb'  revieweridemail =   'onageeb@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Prosares Support-1'    revieweridemail =   't_prosaressupport@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sri Ram Yellajoayula'  revieweridemail =   'SYELLAJOSYULA@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Vijaykumar Julfiram Mehra' revieweridemail =   'VMEHRA@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Muhammed Shafeeque Elayedath'  revieweridemail =   'melayedath@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Emre Ustun'    revieweridemail =   'eustun@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Mathur Ravi Kumar' revieweridemail =   'mkumar@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Shaik Feroz'   revieweridemail =   'sferoz@iffco.com'  saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Rooman Amir Qureshi'   revieweridemail =   'RQURESHI@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Morgan Achiche'    revieweridemail =   'MACHICHE@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Najumudheen Pocker'    revieweridemail =   'NPOCKER@iffco.com' saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Moharana Rajib'    revieweridemail =   'mrajib1@iffco1.onmicrosoft.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Parminder Chopra'  revieweridemail =   't_pchopra@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Reshma M'  revieweridemail =   't_reshmam@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Kavya M'   revieweridemail =   't_kavyam@iffco.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Akshay Pattar' revieweridemail =   't_apattar@iffco.com'   saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )
( reviewer =    'Sharepoint Admin'  revieweridemail =   'shadmin@iffco1.onmicrosoft.com'    saleshead =     'NA'    salesheademail =    'NA'    financereviewer =   'NA'    financerevieweremail =  'NA' )


 ).




    DELETE FROM ztab_sales_head
    WHERE reviewer ='Akshay Pattar'.

*   insert the new table entries
*    INSERT ztab_sales_head FROM TABLE @itab.

*   output the result as a console message
    out->write( |{ sy-dbcnt } Sales Head entries inserted successfully!| ).


  ENDMETHOD.

ENDCLASS.
